### PR TITLE
pep8 and typos

### PR DESCRIPTION
**Pull request by ocefpaf**
@BibMartin hopefully I did not break anything.

This PR is mostly "janitorial services."  Nothing new is introduced and if you think there is too much noise just close it and I will try to send it in small pieces.

### CODE REVIEW

**Comment by BibMartin** [comment]
@ocefpaf 
That's awesome (and I definitely have to learn PEP8 and Englidh)!
I'm not finished with reviewing but everything seems good so far.

Please tell me ; you've got a tool to automate that, don't you ?

**Comment by BibMartin** [comment]
It's okay. I guess it's no need to wait for further review. Let's merge.

**Comment by BibMartin** [comment]
Thank you @ocefpaf !

**Comment by ocefpaf** [comment]
> That's awesome (and I definitely have to learn PEP8 and English)!

Your English is better than mine! 
And if you start pep8ing your code I won't have a place here :wink:

Worry about awesome code and I will clean the mess after the party.

> Please tell me ; you've got a tool to automate that, don't you ?

I use `vim-flake8` to flag what needs changing, but the actual change is manual.  I avoid autopep8.

**Pull request merged**
