### PR TITLE
Add control_scale option

### PR DESCRIPTION
**Pull request by BibMartin**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Awesome!

http://nbviewer.jupyter.org/gist/ocefpaf/8f78beb9f1779a152836

Thanks @jelmelk for starting this at #270

**Comment by BibMartin** [comment]
@ocefpaf These days you may use `lon, lat = -48.566, -27.596` in your examples :wink:

**Comment by ocefpaf** [comment]
> @ocefpaf These days you may use lon, lat = -48.566, -27.596 in your examples :wink:

Yeah.  I forget about the `lonlat` keyword!

**Comment by BibMartin** [comment]
> > @ocefpaf These days you may use lon, lat = -48.566, -27.596 in your examples :wink:

> Yeah. I forget about the lonlat keyword!

I meant centering the examples on Florianopolis.

**Comment by BibMartin** [comment]
btw : thanks for the merges

**Comment by ocefpaf** [comment]
Ouch, I did not even recognized the position.  I don't live there.  But I will be there for the event!

**Pull request merged**
