### PR TITLE
Fix Stamen Toner URL to use .png as stated at maps.stamen.com. Update…

### PR DESCRIPTION
**Pull request by tahmed42**
… different attribution required specifically for Toner as also stated there.

### CODE REVIEW

**Comment by ocefpaf** [comment]
At Stamen Toner I see exactly what we have now:

tiles

However, the OpenStreetMaps [FAQ](http://wiki.openstreetmap.org/wiki/Legal_FAQ) states:

> Our requested attribution is "© OpenStreetMap contributors".
You must also make it clear that the data is available under the Open Database Licence. This can be achieved by providing a "License" or "Terms" link which links to www.openstreetmap.org/copyright or www.opendatacommons.org/licenses/odbl.

So I guess we have to change all maps `attr.txt` that makes reference to OpenStreetMaps!

@tahmed42 Are you willing to do that in this PR?

PS: Are there any advantages of using PNG instead of JPEG?  I find that JPEGs tiles are usually easier on the bandwidth than PNGs.

**Comment by ocefpaf** [comment]
Thanks @tahmed42!

**Comment by tahmed42** [comment]
No problem!

Weird, at maps.stamen.com, they say:
For Toner: Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.
For everything else: Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under CC BY SA.

But maybe *they're* out of date on that and OSM requires ODbl for everything now.
Also re: png, the only reason I made the change to that is because at maps.stamen.com towards the bottom in the "Elsewhere" section, it stated:
Many applications and libraries understand the notion of map URL templates. These are ours:
http://tile.stamen.com/toner/{z}/{x}/{y}.png
http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg
http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg

So it went out of its way to use png for toner and I read that as jpg not being available for it (maybe it was available in the past?). Moreover though, I noticed toner wasn't loading right in folium but with the change to png, it worked. Tested that out using the custom tileset abiilty in folium, which came in super handy.

**Comment by ocefpaf** [comment]
> But maybe they're out of date on that and OSM requires ODbl for everything now.

Yep.  I opened an issue for it #202.

**Comment by tahmed42** [comment]
Ah whoops, didn't catch your comment edit before replying about pngs, haha.

**Comment by ocefpaf** [comment]
No problem.  Thanks again for the PR!

**Pull request merged**
