### PR TITLE
Rationalize Templates

### PR DESCRIPTION
**Pull request by themiurgo**
This is a first attempt at rationalising folium templates, leveraging Jinja's awesome features (http://jinja.pocoo.org/docs/dev/templates/#template-inheritance) and avoid code duplication and bugs (such as #105).

@ocefpaf could you take a look at this once you come back from SciPy? :smiley: 

I have tested the simple folium template and it seems to be working as normal. We should also test the geojson and see if it has any problems.

### CODE REVIEW

**Comment by themiurgo** [comment]
(Btw the PR obviously is not ready yet, just submitted to have a head start ;) )

**Comment by BibMartin** [comment]
This much more elegant than the `render_html` methods etc.

I'm a bit afraid of two things :
* Jinja stuff is quite abstract ; won't it discourage begginners (like I) to get into programming plugins ?
* I cannot figure out how the code would behave if I wanted to combine several plugins. Like for example:

        map = folium.Map()
        map.add_plugin(MarkerCluster(...))
        map.add_plugin(ScrollZoomToggler(...))
        map._repr_html_()

**Comment by themiurgo** [comment]
> Jinja stuff is quite frightening ; won't it discourage begginners (like I) to get into programming plugins ?

Jinja was made for desiners and in general it was made to be simpler than Python coding. I think it should be enough to write that docs page

> I cannot figure out how the code would behave if I wanted to combine several plugins. Like for example:

The code I've pushed does not deal with plugins so I can't answer that. I will answer your question about plugins in the other thread.

**Comment by ocefpaf** [comment]
I like the idea of having a `base` and injecting that into the `geojson` and any other plugins.  However, I am unsure how the current plugin plan fit in here.  @themiurgo can you rebase this?

@BibMartin can you take a second pass at this in light of your plugin branch?

**Comment by themiurgo** [comment]
I'll take a look at it this or the coming weekend (sorry, deadlines and holidays to sort out first) :stuck_out_tongue_closed_eyes:

**Comment by ocefpaf** [comment]
How are we on this?  Is it worth re-basing and merging or does #170 changed the game?

I am sorry for not participating on this as much as I should.  But I got some free time and I want to fix that :wink:

**Comment by ocefpaf** [comment]
ping!

**Comment by themiurgo** [comment]
It's probably good to see what @BibMartin has to say about this, whether this PR still makes sense to be merged and how it relates to the last changes in the codebase.

**Comment by ocefpaf** [comment]
@BibMartin I guess that this does not fit in the latest code, correct?

@themiurgo are you OK closing this?

PS: Before closing let's just check if we can steal any ideas  :wink:

**Comment by BibMartin** [comment]
It does not fit in the lastest code, but the concern of rationalizing templates is still relevant.

In the latest code, most template code is written inside python code (with triple quotes) and most templates are either not used or used in tests only. Though this is not uniformely true. I think a coming question is : do we want to generalize this mindset, or to separate python code and templates ?

**Comment by ocefpaf** [comment]
> I think a coming question is : do we want to generalize this mindset, or to separate python code and templates ?

I like the templates inside the code like you are doing.  Life is much easier that way :wink: 

Unless someone brings a good reason not to do so let's move in that direction.

We need a PR to remove the unused templates and/or updated the tests.

Closing this.

**Comment by themiurgo** [comment]
Yes, I was ok closing this. Perhaps in the future we'll do again something similar.

**Comment by ocefpaf** [comment]
> Perhaps in the future we'll do again something similar.

:+1:

**Pull request closed without merging**
