### PR TITLE
ADD popups, iconstyle, date formatting to timedimension

### PR DESCRIPTION
**Pull request by ghandic**
Added the ability to have popups, choose your icon style (or circle style) and formatted date for human readability

added another JS libarary to do this - moment.js

- happy to document this and create an example if it is accepted

### CODE REVIEW

**Comment by ocefpaf** [comment]
Hi @AndyChallis1, thanks for the PR!

Can you please remove all the `.pyc`, `egg`, and `.DS_Store` to make it easier to review the actual changes? It would be nice if you could create a notebook example demonstrating this functionality.

**Comment by AndyChallis1** [comment]
I tried to remove those files - I'm relatively new to git and assumed there would be a .gitignore file, is this worth adding?

**Comment by AndyChallis1** [comment]
I've added an example in Plugins.ipynb

**Comment by ocefpaf** [comment]
> I tried to remove those files - I'm relatively new to git and assumed there would be a .gitignore file, is this worth adding?

I don't really like global `.gitignore` because I do like to customize them locally depending on what I am doing. I also discourage the use of `git add -A`.

Thanks for the PR update! I will try to review it as soon as possible,

**Pull request closed without merging**
