### PR TITLE
#1742 allowing Choropleth key_on to traverse through array

### LINKED ISSUE #1742: Choropleth key_on doesn't allow for traversing an array
**Is your feature request related to a problem? Please describe.**
Can't match based on a property which hides the property you need in an array. Such as the following in a geojson for Canadian provinces I want to use:

```json
"properties":{
   "geo_point_2d":{
      "lon":-114.51101438986483,
      "lat":55.16890299842028
   },
   "year":"2021",
   "prov_code":[
      "48"
   ],
   "prov_name_en":[
      "Alberta"
   ],
   "prov_area_code":"CAN",
   "prov_type":"province",
   "prov_name_fr":"Alberta"
}
```

I'm not sure why this hides the English province name in an array, but if I've run into this I'm sure it could be an issue for someone else at some point too.

**Describe the solution you'd like**

Either `feature.properties.prov_name_en.0` or `feature.properties.prov_name_en[0]` should work.

**Describe alternatives you've considered**

Alternatives above, short of implementation I must modify the file for now.

**Additional context**

**Implementation**
folium is maintained by volunteers. Can you help make a PR if we want to implement this feature?

I would consider helping with PR if given guidance on preferred implementation.

### PR DESCRIPTION
**Pull request by amrutharajashekar**
closes #1742

### CODE REVIEW

**Comment by Conengmo** [comment]
Thanks Amrutha! I'll take a closer look shortly. Just wanted to say already it would be good to add a test for `get_by_key`. That would require moving it up a level so it becomes a 'proper' method on the class. Since it's not for consumption also make it private by prepending an underscore: `_get_by_key`.

**Comment by amrutharajashekar** [comment]
Thanks for the pointers Conengmo , will work on them over the weekend and get back to you!

**Comment by amrutharajashekar** [comment]
Hi @Conengmo How do we test for pre-commit check locally ?

**Comment by martinfleis** [comment]
@amrutharajashekar 

You must first install pre-commit:

```sh
pip install pre-commit
```

From the root of the folium repository, you should then install the pre-commit included in Folium:
```sh
pre-commit install
```
Then checks will be run automatically each time you commit changes. You can skip these checks with `git commit --no-verify`.

**Comment by amrutharajashekar** [comment]
Hi Conengmo, I have made _get_by_key private and included the test case for the same, Please check this and let me know if any other changes are required. Thanks !

**Comment by Conengmo** [comment]
Great! I’ll take a look on Monday.

**Comment by Conengmo** [comment]
Hi @amrutharajashekar, I added a commit to your PR, hope you don't mind. Your change is good, but since we're touching this code anyway I tried to get rid of some of the repeat logic, make it a bit easier to read. I also added the 'regular' path to the test. If you are okay with this I'll go ahead and merge this one!

**Comment by Conengmo** [comment]
@amrutharajashekar thank you very much for your help!

**Pull request merged**
