### PR TITLE
Add CRS map option

### PR DESCRIPTION
**Pull request by BibMartin**
addresses #8 

See http://nbviewer.ipython.org/github/bibmartin/folium/blob/crs/examples/CRS%20comparison.ipynb

### CODE REVIEW

**Comment by ocefpaf** [comment]
Nice!

**Comment by ocefpaf** [comment]
I need to read the docs on the CRS use in leaflet to see if we can add that option to other objects.

Like a GeoJSON that is not on `EPSG3857`, but can be re-project to it on the fly.  (Not sure if that is possible in leaflet though!)

**Comment by BibMartin** [comment]
Seems it's possible with GeoPandas ; but it looks quite buggy for the moment.
At least, it would add dependency to `pyproj` and I guess it's a good reason to let this ouside of folium.

**Comment by ocefpaf** [comment]
Merging this.

Thanks @BibMartin!

**Pull request merged**
