### PR TITLE
write_png fix!

### PR DESCRIPTION
**Pull request by andrewgiessel**

### CODE REVIEW

**Comment by andrewgiessel** [comment]
@ocefpaf your example notebook works locally now!  This slipped through because the code oddly worked before in the case of using square arrays (width and height are equal).  We also needed to flip the array up down to make it make sense.

**Comment by andrewgiessel** [comment]
I can tag on some other doc string edits, too, if this works for you

**Comment by ocefpaf** [comment]
Merged!  Thankss @andrewgiessel!

**Comment by ocefpaf** [comment]
> I can tag on some other doc string edits, too, if this works for you

It is working with that example and I am creating more examples here.  (Like plots generated from Basemap and cartopy as overlays.)

Lets fix the docstrings in another PR.  I also want to discuss:

- The use of `None` as the default projection.  You can see that something is weird in the image I used;
- The default `opacity = 1`;
- Full example where the projections makes a difference;
- Less wordy docstrings.

After that we should release `v0.1.6`.  (And then start porting this as a plugin :stuck_out_tongue_winking_eye: )

**Comment by andrewgiessel** [comment]
Cool, I'll open an sane default / docstring PR.

How did your other examples go?

**Comment by ocefpaf** [comment]
> How did your other examples go?

Not ready yet...  I lost my weekend window.  Now that will have to until... The day job is calling!

**Pull request merged**
