### PR TITLE
Removed deprecated methods from examples and code snippets

### PR DESCRIPTION
**Pull request by glfharris**
Brought a couple of the examples and the readme into the new methods scheme. As the underlying functionality is the same, this is mostly just for convenience/aesthetics. Just removes some confusion from people using folium for the first time.

Also altered the data paths for the Antartic shelf example so that it now functions. At a guess this was left over from a previous file structure.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Awesome PR! Thanks @glfharris!!

**Comment by ocefpaf** [comment]
The failures are only `pep8` compliance stuff:

```shell
1.48s$ find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100
./examples/choropleth_states.py:17:17: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:18:17: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:19:17: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:20:17: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:26:18: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:27:18: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:28:18: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:29:18: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:30:18: E128 continuation line under-indented for visual indent
./examples/choropleth_states.py:31:18: E128 continuation line under-indented for visual indent
```

**Comment by glfharris** [comment]
Accidentally altered the wrong file, but reverted. choropleth_counties.py has some issues with key errors, but that requires digging down into the data source, which is why I haven't touched it.

PEP8 formatting should be fixed.

Cheers!

**Comment by ocefpaf** [comment]
The remaining issue has nothing to do with your PR and I will fix that later. Thanks again @glfharris!

**Pull request merged**
