### PR TITLE
Fix issue #252

### PR DESCRIPTION
**Pull request by BibMartin**
For the pleasure to do a 2 characters PR.
Tests will come later

### CODE REVIEW

**Comment by ocefpaf** [comment]
I wonder if I will have time to read all those changes!!!

**Comment by themiurgo** [comment]
:grinning:

**Comment by ocefpaf** [comment]
I am merging this, but let's leave #252 open until we have some tests.

BTW I tested this and it works. I did not know about `|e`.  Awesome to learn something new!  I was going to use the messy `.encode('ascii', 'xmlcharrefreplace')` like we had before.

**Comment by BibMartin** [comment]
>  I did not know about |e. Awesome to learn something new! 

It's new to me also ; thank you duckduckgo. But it does not transform non-ASCII characters. Try with `"Ça c'est chouette"`. I guess there's something about encoding/decoding things also.

**Comment by ocefpaf** [comment]
>  But it does not transform non-ASCII characters. 

Good to know.  I am trying to design tests for this and I will add a failing test for `Ça c'est chouette`.

**Comment by ocefpaf** [comment]
Thanks @BibMartin!  I am writing some tests for test.  Hopefully I will have something ready tomorrow.

**Comment by themiurgo** [comment]
This is amazing. One issue closed in a few hours. :)

**Comment by ocefpaf** [comment]
Well.  Let's not close the issue until we have the tests in place :smiley_cat:

**Pull request merged**
