### PR TITLE
Less boilerplate for optional dependencies

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR reduces the amount of code when adding an optional dependency.  I do not think we have anything like this outside `folium/utilities.py`.

I think we should follow this simpler pattern in the future.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@BibMartin this is not aimed to close #241 per se. But let me know if you are OK with this as a strategy deal with optional dependencies.

**Comment by BibMartin** [comment]
@ocefpaf 
I'm not fully okay with this strategy. I'd prefer if the *buggy* functions were isolated into a plugin.
For example, I guess `ImageOverlay` would need to be a plugin (or at least the `array->image` part), so that the plugins would be tagged **numpy dependent**, while there's no risk of facing a bug when using *classical folium*.

**Comment by ocefpaf** [comment]
> I'm not fully okay with this strategy. I'd prefer if the buggy functions were isolated into a plugin.
For example, I guess ImageOverlay would need to be a plugin (or at least the array->image part), so that the plugins would be tagged numpy dependent, while there's no risk of facing a bug when using classical folium.

That is better.  Still, even as isolated plugins, I'd rather we import inside the function and let the `ImportError` be raised, than suffering the risk of a rogue import somewhere triggering the optimal dependency.

We can close this, leave as-is, and open another issue to isolated things.  Or we can merge this, ship `v0.2.0` and work on isolating things in `v0.2.1`.  Your call.  I am fine either way.

**Comment by themiurgo** [comment]
I'm with @BibMartin for long-term strategy on this.

**Comment by ocefpaf** [comment]
I closed this. We'll follow with @BibMartin's strategy.

**Pull request closed without merging**
