### PR TITLE
Fix key error in choropleth (#402)

### PR DESCRIPTION
**Pull request by BibMartin**
#402

### CODE REVIEW

**Comment by ocefpaf** [comment]
I almost forgot about this one! Thanks @BibMartin!!

**Comment by psychemedia** [comment]
I've noticed that if I'm trying to colour a map and a key that exists in the geojson file isn't matched by a corresponding key in the data file, I get a similar error:

folium.__version__
'0.2.0.dev'

Call of form:

````
m2 = folium.Map([centre_lon,centre_lat], zoom_start=11)
m2.choropleth(
    geo_path=geojson_local,
    data=mapdata,
    columns=['PSCHO001', 'diff13_07'],
    key_on='feature.properties.LSOA11CD',
    fill_color='PuBuGn', fill_opacity=1.0
    )
m2
````

Error:

````
/Users/ajh59/anaconda/lib/python2.7/site-packages/jinja2/runtime.pyc in call(_Context__self, _Context__obj, *args, **kwargs)
    194                 args = (__self.environment,) + args
    195         try:
--> 196             return __obj(*args, **kwargs)
    197         except StopIteration:
    198             return __self.environment.undefined('value was undefined because '

/Users/ajh59/anaconda/lib/python2.7/site-packages/folium/features.pyc in style_data(self)
    268         for feature in self.data['features']:
    269             feature.setdefault('properties',{}).setdefault('style',{}).update(
--> 270                 self.style_function(feature))
    271         return json.dumps(self.data)
    272 

/Users/ajh59/anaconda/lib/python2.7/site-packages/folium/folium.pyc in <lambda>(x)
    608             "color" : line_color,
    609             "fillOpacity" : fill_opacity,
--> 610             "fillColor" : color_scale_fun(x)
    611             }
    612 

/Users/ajh59/anaconda/lib/python2.7/site-packages/folium/folium.pyc in <lambda>(x)
    599                                                            '.'.join(key.split('.')[1:])))
    600             color_scale_fun = lambda x: color_range[len([u for u in color_domain
--> 601                                                          if u<=color_data[get_by_key(x,key_on)]])]
    602         else:
    603             color_scale_fun = lambda x: fill_color

KeyError: u'E01033229'
````

When working with civic datasets, it may be the case that some area codes are occasionally missed or change. It would be useful elements in the geojson that are unmatched by area codes in the data to be coloured with a default missing colour or texture.

My workaround was to find missing keys and add them to the dataframe, but that's not ideal.

````
import json
keys=[k['properties']['LSOA11CD'] for k in json.load(open('E06000046.json'))['features']]
missing.keys=set(keys)-set(iwprimary07_13['PSCHO001'])
...
dicts=[]
for k in set(keys)-set(iwprimary07_13['PSCHO001']):
    row={}
    dicts.append({'PSCHO001': k, 'diff13_07': 0})

mapdata = mapdata[['PSCHO001', 'diff13_07']]
mapdata=mapdata.append(dicts, ignore_index=True)
````

**Comment by ocefpaf** [comment]
> '0.2.0.dev'

You need latest master to include this PR and get the fix. I will work on a new release soon.

**Comment by psychemedia** [comment]
Noted - thanks:-)

**Pull request merged**
