### PR TITLE
docs: rework Plugins page into a tabular format

### LINKED ISSUE #1887: Improve the Plugins documentation by including a one-liner for each available plugin
**Is your feature request related to a problem? Please describe.**
Upon visiting the [`user_guide/plugins`](https://python-visualization.github.io/folium/latest/user_guide/plugins.html) page, I found myself with a bunch of hyperlinks to different plugins available within folium. While the name suggests what the plugin does, as a user, I will find an accompanying one-liner summary very useful.

**Describe the solution you'd like**
A table with two columns: `Plugin` and `Description` where the former contains the hyperlinked names and the latter should have a one-liner description.

**Describe alternatives you've considered**
`user_guide/plugins` is kept as it is and [a more verbose] description is added in their respective pages.

**Additional context**
None

**Implementation**
Absolutely

### PR DESCRIPTION
**Pull request by achieveordie**
Fixes #1887

**Summary**:
- Separate `Antpath` and `PolyLineTextPath` usage markdown files for better readability.
-  Convert the plugins page into a tabular format with hyperlinked names and the corresponding descriptions.

**The old representation**:
old

**The new representation**:
new

### CODE REVIEW

**Comment by achieveordie** [comment]
`CHANGES.txt` is failing on the pre-commit check which is weird since that file has not been changed. Perhaps it is being carried on from a previous merge?

**Comment by achieveordie** [comment]
Cannot replicate it locally either, but found a different file which wasn't touched before. Perhaps a difference between the local and CI `pre-commit` might be causing these?

image

**Comment by Conengmo** [comment]
I see it the precommit fails on main as well, that's my fault, sorry! I edited that file in the web UI. I'll fix that soon, but you can ignore it here.

**Comment by Conengmo** [comment]
This looks really good btw, I'll take a closer look asap but on first glance this should be easy to merge!

**Comment by achieveordie** [comment]
> I fixed it on main so if you update your branch, tests should pass. Again apologies!

Done! :)

**Comment by Conengmo** [comment]
Thanks!

**Pull request merged**
