### PR TITLE
Add a "no tiles" option

### PR DESCRIPTION
**Pull request by ocefpaf**
See #249.

### CODE REVIEW

**Comment by BibMartin** [comment]
Simple, clean. Thanks @ocefpaf .

**Comment by ocefpaf** [comment]
I am not sure if we can change the grey background to another color though.  But this will be a niche feature anyways.

**Comment by BibMartin** [comment]
An ugly hack: if you want a white background, you can create a Layer pointing to white tiles.

```python
# Create a white image of 4 pixels, and embed it in a url.
white_tile = folium.utilities.image_to_url([[1,1],[1,1]])

# Create a map using this url for each tile.
m = folium.Map(tiles=white_tile, attr='white tile')
```

**Comment by BibMartin** [comment]
I don't think it shall be embeded in folium, but it's good to remember.

**Comment by ocefpaf** [comment]
> I don't think it shall be embeded in folium,

Agree.

> but it's good to remember.

:+1: (That actually gave me a few crazy ideas :wink:)

**Comment by BibMartin** [comment]
>  (That actually gave me a few crazy ideas :wink:)

Yeah ; like:

```python
tile = folium.utilities.image_to_url([[(-1)**((i+j)//30) for i in range(300)] for j in range(300)])
tile = folium.utilities.image_to_url([[(-1)**((i//30+j//30)) for i in range(300)] for j in range(300)])
```

**Comment by ocefpaf** [comment]
I really like the second one:

http://nbviewer.ipython.org/gist/ocefpaf/efcf54d0a3710b324b60

**Pull request merged**
