### PR TITLE
Support for Vector Grid

### PR DESCRIPTION
**Pull request by mumeraltaf**
Addressing #937 and #563. Added a function to add vector tiles as base layer (namely protobuf) to a map.
Using [VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid) plugin.
Usage Example: examples/VectorGrid.ipynb

### CODE REVIEW

**Comment by ocefpaf** [comment]
@mumeraltaf sorry for the long time to review this. Nice stuff and great feature you have here but have you considered creating an external plugin and depend on folium instead?

The reason I say this is b/c we won't be able to maintain the code. I would also recommend you pinning the `folium` version to ensure the plugin won't break with new updates. (Something you cannot do if this is part if the main `folium`.)

**Comment by Conengmo** [comment]
I think this PR is nicely done, code looks good. I'm inclined to include this in the repository because:

- It's not that heavy in code
- The underlying library is in the Leaflet github organization
- and seems to be actively maintained

I would propose to move it to it's own plugin module though, since the appeal is not that broad (I assume) and technically it is a plugin.

Also the two methods in `Map` should be removed.

Here are links to the two notebooks, which aren't working it seems by the way:
http://nbviewer.jupyter.org/github/AURIN/folium/blob/master/examples/VectorGrid.ipynb
http://nbviewer.jupyter.org/github/AURIN/folium/blob/master/examples/VectorChoropleth.ipynb

**Comment by RenoFilla** [comment]
OK, so has this functionality been picked up anywhere yet? I like to display airspace using OpenAIP (https://maps.openaip.net) which is a vector tile layer as far as I can see: 

var OpenAIP = L.tileLayer('http://{s}.tile.maps.openaip.net/geowebcache/service/tms/1.0.0/openaip_basemap@EPSG%3A900913@png/{z}/{x}/{y}.{ext}', {
	attribution: '<a href="https://www.openaip.net/">openAIP Data</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-NC-SA</a>)',
	ext: 'png',
	minZoom: 4,
	maxZoom: 14,
	tms: true,
	detectRetina: true,
	subdomains: '12'
});

**Comment by Conengmo** [comment]
This PR is very stale, so I'm going to close it now. This feature is still welcome, so if somebody wants to pick up the work here and address the comments (https://github.com/python-visualization/folium/pull/943#issuecomment-441462510) in a new PR that would be appreciated!

**Comment by Conengmo** [comment]
This was also partially implemented in https://github.com/python-visualization/folium/pull/1576, available in the 0.13.0 release.

**Pull request closed without merging**
