### PR TITLE
Fix Travis-CI

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR:

1. fixes for Travis-CI (`pytest` was failing due to a change in how the latest `setuptools` passes arguments)
2. Adds Python 3.5 to the test matrix
3. Import workaround for mock on python 3.5
4. PEP8 `test_folium.py` (Sorry for the noise the important change is in 3)
5. Clean the change log up
6. Bump master to `0.2.0.dev`

@BibMartin or @andrewgiessel can you review and merge this please?

### CODE REVIEW

**Comment by BibMartin** [comment]
It seems good to me (sorry I realise I'm not a good pep8er)
Merge in 2 days when I'm back home.

**Comment by ocefpaf** [comment]
> sorry I realise I'm not a good pep8er

Good!  It means I still have a role here :wink:

**Comment by themiurgo** [comment]
Seems good to me as well! Merged! :+1:

**Comment by ocefpaf** [comment]
Thanks @themiurgo!  Awesome to see you around here!!  Is the day job giving you a break?  :wink:

**Comment by themiurgo** [comment]
Kind of :smile:

**Pull request merged**
