### PR TITLE
scale control

### PR DESCRIPTION
**Pull request by jelmelk**
https://github.com/python-visualization/folium/issues/268

Added it to the `Map` class. Shows up on bottom left.

### CODE REVIEW

**Comment by BibMartin** [comment]
Wow @jelmelk ; a PR just a few minutes after the issue's report !

I think this would worth being in a separate plugin ; otherwise you force *everyone* to have the control.scale on his map. You can find inspiration in other plugins (like https://github.com/python-visualization/folium/blob/master/folium/plugins/terminator.py).

Provided that you're also working on #265 and #267 ; tell me if you want I do a part of the job :wink:

**Comment by ocefpaf** [comment]
> Wow @jelmelk ; a PR just a few minutes after the issue's report !

Awesome!  Thanks for the PR @jelmelk!

> I think this would worth being in a separate plugin

:+1: 

@jelmelk the key is the [template](https://github.com/python-visualization/folium/blob/master/folium/plugins/terminator.py#L32-L36).  Note that you do not have any extra `JavascriptLink` in this case.

> tell me if you want I do a part of the job

@jelmelk I am sure @BibMartin would do this in quickly, but we (myself included) most learn the new "pluginified way" to do things in folium `v0.2.0`.

So I recommend you take your time and ask for help as much as you need to get this ready on this PR.  It will be worth the effort in the long run :smile:

**Comment by jelmelk** [comment]
> I think this would worth being in a separate plugin ; otherwise you force everyone to have the control.scale on his map. 

It seemed that it's something minor, same as the zoom control. But if it needs to be a separate plugin so be it, if you don't mind tackling that @BibMartin then I'll pay attention on how you do it as a future reference.

>@jelmelk I am sure @BibMartin would do this in quickly

Isn't that the truth :laughing: 

As far as https://github.com/python-visualization/folium/pull/265, not only I ruined the PR by overlapping additional ones it'll take me longer to get something like that done, so it's up to you @BibMartin.

For https://github.com/python-visualization/folium/pull/267 I'm 100% on board.

**Comment by BibMartin** [comment]
I'm in line with @ocefpaf's concern
> but we (myself included) most learn the new "pluginified way" to do things in folium v0.2.0.

But you're doing a great doc job in #267 and I guess this is the main priority before `v0.2.0` release.

I'll finish up the #265 to help, and *leave this PR to you as an exercise* (I've never been teaching, but always dreamt to say that) ; provided there's no hurry on it.

**Comment by jelmelk** [comment]
@BibMartin thank you for your help. I'll take it easy on PR for adding features while I learn the process.

**Comment by ocefpaf** [comment]
> @BibMartin thank you for your help. I'll take it easy on PR for adding features while I learn the process.

:+1:

**Comment by ocefpaf** [comment]
@BibMartin coming back to this I don't think we should add this as a plugin.  In the [`L.control.scale`](http://leafletjs.com/reference.html#control-scale) has no customization options.  It is simple a True/False thing.

Maybe this a case where we could overload the Map() initialization with a new `kwarg` (`control_scale=False/True`).  What do you think?  If so, @jelmelk are you wiling to resurrect this PR, implement the `kwarg`, and add a test for both cases?

**Comment by ocefpaf** [comment]
@BibMartin bringing this back to your radar.  What do you think of my comment above?  If you agree we can add this to `v0.2.0`.

**Comment by BibMartin** [comment]
Ok, see #355

**Comment by ocefpaf** [comment]
Closing in favor of #355.  Thanks @jelmelk!

**Comment by berrfred** [comment]
It looks like L.control.scale() now has several useful options  (e.g. position. metric, imperial), wouldn't it make sense to have it as a separate plugin as initially suggested by @BibMartin ?

I am interested in showing only the metric scale at bottomrigth ... and maybe trick the css to integrate it in the attributions but this is another story.  Today it would require some dirty css and js to achieve it.

**Comment by berrfred** [comment]
This is where I got with my usual script approach, moving control-scale to bottomright before attribution and assuming imperial is the second child, then delete it:

```python
map_script_scale_control = '<script>document.addEventListener("DOMContentLoaded", function() {\
	var leafletControlScale = document.querySelector("div.leaflet-control-scale");\
	document.querySelector("div.leaflet-bottom.leaflet-right").insertBefore(\
		leafletControlScale, document.querySelector("div.leaflet-control-attribution")\
	);\
	leafletControlScale.removeChild(leafletControlScale.children[1]);\
});</script>'

map.get_root().html.add_child(folium.Element(map_script_scale_control))
```

image

**Pull request closed without merging**
