### PR TITLE
Untoggle overlays and additional base layers

### PR DESCRIPTION
**Pull request by Conengmo**
I worked on solving issue #606 and #571. I added functionality in the `LayerControl` class to untoggle overlays that have `hidden=True`. While I was there I simplified the checks in render(). If an item is an instance of `Layer` it will always have the `overlay` and `control` attributes.

I added the `hide` parameter to some classes to test it out, but not to all children of `Layer` yet.

What do you guys think, is this a good way to do this?

### CODE REVIEW

**Comment by ocefpaf** [comment]
> What do you guys think, is this a good way to do this?

Yep. That fits `folium` perfectly. Thanks!

Can you:

- add the keyword to everything else that inherits from `Layer`;
- change the nome from `hide` to... Maybe `toggle`? I accept other suggestions but hide seems like something that won't be displayed ever;
- add an entry to the changelog/

**Comment by Conengmo** [comment]
I added the `show` parameter to all classes that inherit from `Layer`. At least, I hope I got them all :)
`show` seemed a good choice, I saw it's also being used in #778.

I noticed `Heatmap` and `HeatMapWithTime` inherited from `TileLayer`, that didn't really make sense to me. They also didn't use anything from `TileLayer`. So for consistency I changed both classed to inherit from `Layer`.

I also did some work on the use of `name`, `overlay` and `control` in `__init__` statements and docstrings in files I touched. It should be fairly consistent now.

I didn't test all code I touched. I did test creating some maps with `GeoJson` objects, with `Featuregroup`s, `MarkerCluster`s and `HeatMap`s, and everything seemed to work alright.

Let me know if there's something you want different or added.

**Comment by Conengmo** [comment]
I noticed that [according to Leaflet](http://leafletjs.com/reference-1.2.0.html#control-layers-l-control-layers), any additional base layers should not be added to the map. In Folium all base layers are added to the map. As a result the last base layer is selected in layer control, while the first base layer is displayed.

Fixing this by not adding additional base layers to the map is hard, since we then need to check this in every class that inherits from `Layer`. Removing the additional base layers in `LayerControl` also works, so I added it here.

**Comment by ocefpaf** [comment]
Perfect! Thanks @Conengmo!!

**Comment by carlospendola** [comment]
thanks master! @Conengmo

**Pull request merged**
