### PR TITLE
Update map.py to fix broken unpkg urls

### PR DESCRIPTION
**Pull request by steeznson**
Fixed broken unpkg url

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Just fyi, this might not fix the problem for everyone - lots of people have been complaining about random 404 and 503 unpkg responses recently (e.g. for me the 1.1.0 link works).

You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/leaflet@1.1.0/dist/leaflet.js

**Comment by steeznson** [comment]
Huh I thought that unpkg might have deleted the old version seeing as 1.2.0 is the latest. Anyway thanks for the new url.

**Comment by ocefpaf** [comment]
@steeznson do you to try @MartinKolarik's new URL but still pointing to `1.1.0` version? (I would like to keep the leaflet update to another PR so we can access what has changed first.)

**Comment by steeznson** [comment]
Yes I think @MartinKolarik's url to Leaflet1.1.0 sounds like a good idea.

**Comment by ocefpaf** [comment]
Thanks! I am reserving today for folium. If you make the changes soon I can merge it today. (No pressure though :wink:)

**Comment by steeznson** [comment]
Ok all done! Thanks for reminding me to change it.

**Comment by ocefpaf** [comment]
We need to also update the template used for testing, but I can do that. Thanks for the PR @steeznson!

Feel free to send another one updating folium to leaflet 1.2.0 :wink:

**Pull request merged**
