### PR TITLE
Create crossfilter plugin

### PR DESCRIPTION
**Pull request by BibMartin**
*not ready*

Inspired by @austinlyons 's awesome <a href="https://github.com/austinlyons/dcjs-leaflet-untappd">tutorial</a>, provide an API to create crossfilter maps in folium.

See example at http://nbviewer.ipython.org/github/bibmartin/folium/blob/crossfilter/examples/Crossfilter%20example.ipynb

### CODE REVIEW

**Comment by wrobstory** [comment]
That example is amazing.

**Comment by ocefpaf** [comment]
Nice visualization!

**Comment by ocefpaf** [comment]
Now that https://github.com/BibMartin/crossfolium exists  (awesome BTW!) can we close this PR?

**Comment by BibMartin** [comment]
Yes, it was my intention.

**Pull request closed without merging**
