### PR TITLE
Leaflet global switches

### PR DESCRIPTION
**Pull request by sgvandijk**
Implements #335: Adds ability to set Leaflet's global switches (http://leafletjs.com/reference.html#global)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @sgvandijk! LGTM, but I will wait for @BibMartin opinion before merging.

**Comment by ocefpaf** [comment]
@sgvandijk can you rebase this so we can merge?

**Comment by sgvandijk** [comment]
@ocefpaf done! Looks like I can ignore those errors?

**Comment by ocefpaf** [comment]
> @ocefpaf done! Looks like I can ignore those errors?

Yep. I re-started Travis-CI anyways b/c I like the green button :smile: 

Thanks @sgvandijk!

**Pull request merged**
