### PR TITLE
adding a binder badge

### PR DESCRIPTION
**Pull request by vbergste**
added a binder badge to the examples folder

### CODE REVIEW

**Comment by ocefpaf** [comment]
Hi @vbergste, this is an awesome addition. Thanks for doing it. You will notice the Continuous Integrations tests running below. In this case, because you did not changed the code, you don't need to wait for them to finish to merge it.

**Comment by ocefpaf** [comment]
They @Conengmo, we are at PyCon for a mentored sprint and I will be merging a few PRs like this. Just wanted to let you know.

**Comment by Conengmo** [comment]
Hi @ocefpaf, thanks for the message. Just saw a long list with notifications so I already wondered what was going on :p cool that you’re doing this! Let me know if I can help you with something.

**Comment by ocefpaf** [comment]
> Let me know if I can help you with something.

Take a quick look at PRs #1140 and #1144. It will be nice for the sprint attendees to get feedback from someone off-site (which is 99.99% the time the normal way we do things on GitHub ;-p).

**Pull request merged**
