### PR TITLE
Pin older version of leaflet side by side

### PR DESCRIPTION
**Pull request by jtmiclat**
Addresses issue raised in #1730

### CODE REVIEW

**Comment by martinfleis** [comment]
Do we know what is going on apart from that the latest version does not work? If it is a bug it should be fixed (either here or there), pinning is only a temporary solution.

**Comment by martinfleis** [comment]
Interesting. Are you able to pinpoint the source? If it is leaflet or the plugin and report it there? We can pin it here but we need to track the progress to unpin it once resolved in the upstream.

**Comment by giswqs** [comment]
It seems the `leaflet-side-by-side` plugin is the root cause. 
https://github.com/digidem/leaflet-side-by-side/issues/48

**Comment by giswqs** [comment]
Sent the wrong link. Should be this one: https://github.com/digidem/leaflet-side-by-side/issues/47

**Review by martinfleis — APPROVED** [review]
Approving as a temporary fix until the upstream solution is released. Thanks!

**Pull request merged**
