### PR TITLE
deprecation added

### PR DESCRIPTION
**Pull request by jelmelk**
To address this https://github.com/python-visualization/folium/issues/269

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @jelmelk!

**Comment by ocefpaf** [comment]
@BibMartin unrelated to this PR I just noticed that the `_repr_html_` is broken when we use `line` or `multiline`.  I will update all the notebooks [here](https://github.com/ocefpaf/folium_notebooks) with latest master and report an issue later.

**Comment by BibMartin** [comment]
Great fast job. Congrats @jelmelk 

@ocefpaf 
>  I will update all the notebooks here with latest master and report an issue later.

:+1: btw, I'm thinking we may incorporate a few example notebooks into the tests, to make sure they still run. Why not using something like <a href="https://pypi.python.org/pypi/runipy">this</a> ?

**Comment by ocefpaf** [comment]
I used `runipy` in the past to test notebook output, but the problem, in this case, are that the changes will be hard to make sense (like diffs of base64 encoded PNGs).

I think we can do an OK job by strengthen our tests as their are and increase html comparisons.  I am sure that the `_repr_html_` in that case has a flaw that we can test.

Or maybe (crazy idea alert) we can add runipy, generate HTMLs, publish them, and inspect them before merging a PR.

**Comment by BibMartin** [comment]
Let's continue this discussion in a dedicated issue #272

**Pull request merged**
