### PR TITLE
Fix heatmap intensity

### LINKED ISSUE #1271: HeatMap doesn't use weights
I spend quite some time tracking down this bug. I think it should be fixed or the limitation should be clearly stated in the docs. This is a major time waster and makes a bad impression for this otherwise great package.

This is a major bug coming for the upstream Leaflet.heat project.

- https://github.com/python-visualization/folium/issues/496
- https://github.com/Leaflet/Leaflet.heat/issues/43
- https://github.com/Leaflet/Leaflet.heat/issues/74

#### Problem description

The `plugins.HeatMap` states that the point used to create the heat map can
be weighted.

```
data (list of points of the form [lat, lng] or [lat, lng, weight])
```

However weights are simply ignored. This makes it useless for heatmaps that are based on a few points with different weights.

#### Expected Output

Weight should have impact. Or remove this option from the docs.

### PR DESCRIPTION
**Pull request by Conengmo**
Closes #1271.

Weights are broken in the heatmap plugin. See the linked issue for more details.

The leaflet.heat dependency seems abandoned. There is [a PR with a fix](https://github.com/Leaflet/Leaflet.heat/pull/78) available, but it's not getting merged. Host this dependency in our repo and include the fix.

*todo*

- [x] put in a userwarning that `max_val` is deprecated and why
- [x] add a selenium test that verifies behavior with weights

### CODE REVIEW

**Comment by Conengmo** [comment]
Do not merge until the JS dependency URL has been updated.

**Comment by Conengmo** [comment]
@ocefpaf could you take a look at this? The issue poster cannot help review it. It's a pretty bad bug though, and has been for some time (https://github.com/python-visualization/folium/issues/1271, https://github.com/python-visualization/folium/issues/496)

**Comment by Conengmo** [comment]
Thanks for checking. About regression tests, how do you feel about having Selenium tests? I have time to add those. But maybe you can say something about making it work in Appveyor?

**Comment by ocefpaf** [comment]
> how do you feel about having Selenium tests?

Those are great!

> I have time to add those.

Awesome!

> But maybe you can say something about making it work in Appveyor?

Just add a pytest mark and skip them on AppVeyor at the moment. I'll investigate later how to run them there. (Or move to AzurePipelines.)

**Pull request merged**
