### PR TITLE
Fixing flake8 warnings

### PR DESCRIPTION
**Pull request by pmains**
Fixing flake8 warnings, except unused folium.features.GeoJsonPopup import and _version.py newline error.

_version.py is not tracked and so changing that would have no effect on the codebase.

The unused import seemed possibly necessary inside of an __init__.py file.

### CODE REVIEW

**Review by Conengmo — APPROVED** [review]
Just check that tests pass before merging

**Comment by ocefpaf** [comment]
@pmains I fixed a few of the tests. Do you mind rebasing this one to get the latest CI config here?

**Comment by ocefpaf** [comment]
Everything is passing now. I'll send a new one to add .pre-commit afer merging this to avoid regressions.

**Comment by Conengmo** [comment]
Forgot to say but thank you @pmains for your work on this PR!

**Pull request merged**
