### PR TITLE
Remove accidental Fiona dependency

### PR DESCRIPTION
**Pull request by hansthen**
Undo adding fiona to requirements.

### CODE REVIEW

**Comment by Conengmo** [comment]
I don't really understand, these changes have already been merged? See https://github.com/python-visualization/folium/commit/8bc6b02c2f8c13050cc2e7517e8e842a15711081, this is a commit to the main branch, so these changes are already there. I'd expect a PR that removes that line in requirements. Or a PR that reverts that commit, then adds only the wanted changes.

**Comment by hansthen** [comment]
I am getting mixed signals here. You say you do not understand, but from your suggestions I get the impression you do. Maybe I over interpret this, but I am left wondering if I did something that you are unhappy about.

**Comment by Conengmo** [comment]
Sorry if I’ve given offense! I didn’t mean to. I’m really a bit confused :) when I look at the ‘files changed’ I see changes that I think are already in the main branch. If I’m not mistaken https://github.com/python-visualization/folium/commit/8bc6b02c2f8c13050cc2e7517e8e842a15711081 is that commit that adds these changes to the main branch. So what is this PR supposed to do? I don’t mean that in a bad way, just trying to understand. Is there some git weirdness going on here?

**Comment by hansthen** [comment]
> Sorry if I’ve given offense! 

No offence taken; sometimes it is hard to communicate via text fields. 

I made the change your requested on the already merged branch. However, I forgot to sync against the main repo first. I should have rebased it first or started from a clean branch.

**Comment by Conengmo** [comment]
That makes sense! Thanks for clarifying and for updating the branch.

**Review by Conengmo — APPROVED** [review]

**Comment by Conengmo** [comment]
I don’t know why that test failed but this can just be merged I suppose.

**Pull request merged**
