### PR TITLE
Added cartodb positron and dark_matter maps.

### PR DESCRIPTION
**Pull request by ocefpaf**
@birdage Can you review and merge this one?

### CODE REVIEW

**Comment by birdage** [comment]
@ocefpaf i will when travis finishes :smile:

**Comment by ocefpaf** [comment]
I just re-based, pep8'd and added an example [here](http://nbviewer.ipython.org/gist/ocefpaf/3daafb2f17b22963b9b7).

@birdage over to you now.

**Comment by birdage** [comment]
@ocefpaf im seeing scroll bars on the right and bottom now tho?

**Comment by ocefpaf** [comment]
> seeing scroll bars on the right and bottom

In the notebook?  That is my `inline_map()` fault.

(BTW:  we need an overhaul in how we display folium maps in IPython.)

**Comment by birdage** [comment]
yeah there are a few things we need to do :smile:

**Comment by ocefpaf** [comment]
Yep.  BTW, can you take a quick look at: #110, #109, #106, and #102.  I have some cahnges lined up but I want to avoid merge conflicts :stuck_out_tongue_winking_eye:

**Pull request merged**
