### PR TITLE
Add Retina Display Support (issue #206)

### PR DESCRIPTION
**Pull request by BibMartin**
I have no retina display ; so I have no possibility to see how Leaflet reacts.
Maybe @francisbautista can confirm that this works.

### CODE REVIEW

**Comment by andrewgiessel** [comment]
I can try it too

**Comment by ocefpaf** [comment]
@andrewgiessel can you review and merge this one too?

**Comment by andrewgiessel** [comment]
Ya let me try tonight!

**Comment by andrewgiessel** [comment]
Ok, this looks good to go!  I verified this 2 different ways:

1) on my laptop and on an external screen, I loaded a test notebook and refreshed the page on both screens.  I could see the size of the tiles were smaller on my laptop than on the external screen.

2) This is kinda cool- you can use chrome's developer tools to go into 'device' mode, where you can simulate changing the resolution, size and network speed (!) the device that loads the page.  Here are two screen shots of doing this with high and low density screen (and low speed to aid in catching the tiles loading)

screen shot 2015-11-03 at 1 00 25 pm

screen shot 2015-11-03 at 12 59 16 pm

So, I think this is good.  Can I merge?  It's one commit- do I need to clean it up at all?

**Comment by ocefpaf** [comment]
> So, I think this is good. Can I merge?

Merge away!

Thanks @BibMartin for the implementation and @andrewgiessel for the review.

**Comment by themiurgo** [comment]
Do you guys know why Leaflet defaults `detect_retina` to false? It shouldn't have any drawbacks so I would be tempted to default it to True on folium.

**Comment by andrewgiessel** [comment]
My guess is bandwidth. Downloading 2x the tiles you can see

**Comment by themiurgo** [comment]
Mapbox-powered maps (FourSquare & co.) and GMaps defaults to True, despite bandwidth. :grinning:

**Comment by ocefpaf** [comment]
I guess that there are other reasons:

https://github.com/Leaflet/Leaflet/issues/1985

**Comment by themiurgo** [comment]
After all, it seems it's beacause of this: "detectRetina is optional (false by default) to prevent map features (like city titles) from being too small to read on retinal tiles" (source: https://github.com/Leaflet/Leaflet/commit/443181af07391cd624f6328ffd9d0e30351642bf). I don't think we care about that, should we turn it on by default?

**Comment by ocefpaf** [comment]
How about the performance issue I mentioned above?

Ironically it happens only on the IPad using Safari:
> I test it too on Android mobile with detectRetina: true, and no problem. Is only for Safari on iOs.

**Comment by themiurgo** [comment]
Sorry, I thought it was solved because I saw "closed". I'll test it and see if still applies, that's an issue from 2013 so it might have been solved from iOS side.

**Comment by ocefpaf** [comment]
I guess it is worth asking that question in the leaflet issue page.

https://github.com/Leaflet/Leaflet/issues/4014

**Comment by themiurgo** [comment]
On my iPhone there were no performance issues. But yes, the text labels are incredibly small and unreadable, I think that is the reason behind that.

**Comment by ocefpaf** [comment]
We have to bare in mind that setting `false` as the default we ensure the results will be the same in any platform, retina or no. By forcing the user to set it to `true` the user acknowledges that he is targeting platforms where that is desired.

**Comment by ocefpaf** [comment]
We have an official answer:

https://github.com/Leaflet/Leaflet/issues/4014#issuecomment-156441089

**Comment by themiurgo** [comment]
Cool, let's leave it as it is. :+1:

**Comment by ocefpaf** [comment]
We should improve the docs though.  Highlighting the option and say why `false` is the default.

**Pull request merged**
