### PR TITLE
Adding animation to Boat Marker plugin

### PR DESCRIPTION
**Pull request by DavidHickman**
Addresses https://github.com/python-visualization/folium/issues/718 by adding optional animation based on the [upstream plugin example](https://github.com/thomasbrueggemann/leaflet.boatmarker). Default animation can be disabled by passing `animate=False`

Also adds [Turf.js](https://github.com/Turfjs/turf/) JavascriptLink and updates name argument for boat marker import.

I hope it helps!!

### CODE REVIEW

**Comment by DavidHickman** [comment]
Closing for now, I'd like to take another look at the options before I reopen.

**Comment by ocefpaf** [comment]
> Closing for now, I'd like to take another look at the options before I reopen.

Looks like you were headed the right way. Ping me when you want to try this again!

**Comment by DavidHickman** [comment]
Thanks for the feedback! I think the options are a little more full-featured now.

**Comment by ocefpaf** [comment]
Awesome! Thanks!!

I won't be able to review this for now b/c of the day job but I should be able to get to it before the end of the year.

**Comment by DavidHickman** [comment]
No problem! I hope it helps!

**Comment by ocefpaf** [comment]
@DavidHickman I tested your branch and I could not get it to work. Am I missing something or is this not ready yet?

PS: can you rebase with latest `master`?

**Comment by Conengmo** [comment]
This PR is quite stale, so I'm going to close it now. If somebody comes along and wants to adopt this work in progress, that's welcome, but I would suggest you release it under your own repository and include a link to it in our documentation and the example notebook. That's because we don't want to support plugins that are heavy with custom code.

**Pull request closed without merging**
