### PR TITLE
add Draw plugin

### PR DESCRIPTION
**Pull request by ocefpaf**
@BibMartin I know you are quite busy but I'd appreciate if you take a look at this.
Specially if you think of a way to get the GeoJSON back as a python variable.

Right now if you click on the object you'll get an JS alert with the GeoJSON.

I tried:

```
var command = "coords='" + coords + "'"
var kernel = IPython.notebook.kernel;
kernel.execute(command);
```

To return a `coords` variable, but that seems to no longer work. It seems that they deprecated it and now the only way to do this is via widgets. Not sure...

See http://nbviewer.jupyter.org/github/ocefpaf/folium/blob/Draw/examples/Draw.ipynb

### CODE REVIEW

**Comment by BibMartin** [comment]
Hi @ocefpaf ,
The PR looks perfect, and the plugin is awesome.
I'll try to have a look about getting the data back in python ; but I'm a bit pessimistic: you have to tell the client browser to send data back to the server and there's no generic way of doing this.
Anyway, it would be notebook-specific.

**Comment by ocefpaf** [comment]
> Anyway, it would be notebook-specific.

Yeah, that is the goal, but I want to avoid telling people to just use `ipyleaflet`  for that.

We could at least try to create a hook to save a GeoJSON file though... That would be helpful too.

**Comment by ocefpaf** [comment]
BTW I used this in the past with success: http://jakevdp.github.io/blog/2013/06/01/ipython-notebook-javascript-python-communication/

**Comment by BibMartin** [comment]
Yes, this has to be updated but may work. A difficulty lies in the fact that our figure is embedded into an Iframe; meaning that you don't have the same javascript environment as the main notebook. We did this to prevent folium and the notebook's javascript to break eachother...

Another workaround could be to go through the API and use something like:

    curl -X PUT --header 'Cookie: ...' -d '{"content":"someText", "type":"file", "format":"text"}' http://my-jupyter-server/api/contents/foo.txt
but you need to configure the auth cookie properly

**Comment by ocefpaf** [comment]
> Yes, this has to be updated but may work. A difficulty lies in the fact that our figure is embedded into an Iframe; meaning that you don't have the same javascript environment as the main notebook.

Totally forgot about that!

> We did this to prevent folium and the notebook's javascript to break eachother...

We should take a look at how ipyleaflet is doing that. Maybe there is not much interference as we expect.

> Another workaround could be to go through the API and use something like:

Seems too hacky, no?

**Comment by ocefpaf** [comment]
@BibMartin I'll merge this as-is now and we can revisit the Python variable integration later. There are people waiting on this functionality.

**Comment by BibMartin** [comment]
:+1:

Shall we open a new issue for this or let #702 hold the question ?

**Comment by ocefpaf** [comment]
#702 is fine. Thanks!

**Comment by lockbucket** [comment]
I don't know if this is possible, but I was thinking of using this on a flask website.  The plugin works fantastic, but is it possible to load to a database instead of a jupyter notebook?  I think that would be an easier commit than a standard jupyter notebook?  I did a google search for pulling this data and found this bookmark which allows a download of the coordinates?

https://bl.ocks.org/danswick/d30c44b081be31aea483

**Comment by ocefpaf** [comment]
> but is it possible to load to a database instead of a jupyter notebook?

Not sure what you mean. I am terrible with databases.

> I did a google search for pulling this data and found this bookmark which allows a download of the coordinates?

That looks awesome! I'll take a look if I can add that functionality.

Better than the current copy-n-paste and while `ipyleaflet` requires global variables this would require a known file name to deliver a similar functionality with the advantaged of having the data outside the notebook JSON.

**Comment by lockbucket** [comment]
RE: Database

I guess what I am trying to figure out is illustrated here:
http://flask.pocoo.org/docs/0.12/patterns/jquery/

when a person clicks on the layer jquery will then run a python command to update a database.  I will try looking into this. 

Thank you for such a wonderful plugin!

**Comment by ocefpaf** [comment]
PR #727 added the export button option. Not exactly what you want but that is a start in you want to create your own plugin based on that.

**Pull request merged**
