### PR TITLE
Pre commit

### PR DESCRIPTION
**Pull request by ocefpaf**
Continuation of https://github.com/python-visualization/folium/pull/1567

### CODE REVIEW

**Comment by ocefpaf** [comment]
@Conengmo, b/c this PR touches  several files I'll leave to you to merge it or not.

**Comment by Conengmo** [comment]
Good initiative!

I understand using pre-commit locally. But what is the Github Action supposed to do, will it fail if pre-commit changes something?

By the way, did you see this warning? https://github.com/python-visualization/folium/actions/runs/3220435260

**Comment by ocefpaf** [comment]
> I understand using pre-commit locally. But what is the Github Action supposed to do, will it fail if pre-commit changes something?

If it fails a user can fix it by reading the error message. We could configure pre-commit-ci to commit the fix but I find that very intrusive and leads to conflicts that may confuse new contributors.

**Review by Conengmo — APPROVED** [review]
Great, thanks for explaining. Let's merge this now and once we've got the open PRs out of the way add the same pre-commit stuff as branca has.

**Pull request merged**
