### PR TITLE
Moves templates to class attributes (#807)

### PR DESCRIPTION
**Pull request by psarka**
NOTE: Conditional on https://github.com/python-visualization/branca/pull/34.
NOTE: Does not fix two unit tests that are failing at HEAD of master branch
NOTE: Does not fix unit test that fails when HEAD of master of branca is used

This pull request moves the _templates from instance  attributes to class attributes. In this way, the templates are only  compiled once (at import time), rather than every time an object is  created. 

This gives a roughly x100 speedup in cases when a large amount of (on  the order of 1000) objects is created (in my example use case going  from kind of annoying 10s to very reasonable 0.1s)  (see python-visualization/folium#807, as well as here python-visualization/folium#808) 

Having templates as class attributes also makes sense from the  conceptual perspective, as they are identical (and never modified) for  all instances.

### CODE REVIEW

**Comment by Conengmo** [comment]
Hi @psarka, because of the great performance increase of this change it would be good to go ahead with merging this PR. Do you want to help out with fixing the conflicts by merging master into your branch?

I'm thinking about what is wise considering publishing. Your PR in branca has already been merged, but not published to PyPI. This PR breaks folium if you don't also have the branca version from master, so we have to be smart. How about:

* Merge this PR. *folium developers must be on branca master to be able to use folium.*
* Publish a new branca version to PyPI.
* Publish a new folium version to PyPI that requires the new branca version.

If breaking folium for developers using the pip version of branca is not acceptable, we should wait with merging this PR until a new version of branca is published to PyPI.

@ocefpaf is publishing a new branca version a possibility?

**Comment by Conengmo** [comment]
Thanks for fixing the conflicts. You're right, the test with branca 0.2 fail because of the templates in init and the tests with branca master fail because some tests in folium haven't been updated to work with changes in branca master.

I think it is best to fix the tests in a separate PR. I tried something in #845, see if the tests for branca master work. 

We'll have to be smart about how to synchronize releases. It seems folium 0.5 works with branca master, so we can first release branca 0.3. Then fix the tests and merge this PR.  Then release folium 0.6 and require branca 0.3.

**Comment by psarka** [comment]
Sounds good to me :+1: 

Let me know if you need my help on any of that.

**Comment by ocefpaf** [comment]
Sorry for the long delay @psarka and thanks for the awesome speed improvement!

**Pull request merged**
