### PR TITLE
Plugins object and a few plugins

### PR DESCRIPTION
**Pull request by BibMartin**
A few devs based on #145. We have :

* A `Plugin` that other plugins can inherit from.
* A `TemplatePlugin` object to develop simple plugins with jinja2.
* A few examples (BoatMarker, Terminator, Layer).
* A notebook of examples for the plugins.

### CODE REVIEW

**Comment by andrewgiessel** [comment]
FWIW, Build fails due to lack of urllib2 on py3.3 and py3.4

**Comment by BibMartin** [comment]
I think this is ready for merge. @themiurgo, @ocefpaf do you think of a next step ? can you merge it, please ?

**Comment by ocefpaf** [comment]
Outstanding work @BibMartin!! I am actually happy I procrastinated doing this for so you could come along and do it much better than I envisioned :stuck_out_tongue_winking_eye:

**Comment by ocefpaf** [comment]
@BibMartin I just added you to folium team.  We have only one rule: Avoid self-merges are much as you can.  Welcome and thanks for this awesome PR!

**Comment by BibMartin** [comment]
Thanks to you ;-)

**Pull request merged**
