### PR TITLE
Skip Python 3.3 in Travis...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and run `flake8` in all files.

@BibMartin easy review and merge.

I am skipping Python 3.3 not because it is failing, but it is a well know distribution for problems and people are recommended to upgrade. By skipping it in our Travis-CI we only get faster results.

### CODE REVIEW

**Comment by BibMartin** [comment]
I'm okay with it ; but there are conflicts due to #348 merge.

**Comment by ocefpaf** [comment]
Rebased! Over to you @BibMartin.

**Comment by BibMartin** [comment]
Appart of https://github.com/ocefpaf/folium/commit/2cba9f558b7623673d04802a047bc498a095078d#commitcomment-16065272 I am  okay for the rest

**Comment by ocefpaf** [comment]
> Apart of https://github.com/ocefpaf/folium/commit/2cba9f558b7623673d04802a047bc498a095078d#commitcomment-16065272 I am  okay for the rest.

I think I got it now.  Sorry for the noise and thanks for the review!

**Comment by BibMartin** [comment]
Again a [question](https://github.com/python-visualization/folium/commit/deb220f434d460ee73734c69072d7371c531f152#commitcomment-16065746)...

**Comment by BibMartin** [comment]
Ok, now.

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
