### PR TITLE
Replace seawater with geographiclib.

### PR DESCRIPTION
**Pull request by QuLogic**
There's no real use of the seawater package for anything seawater-related, but instead it's used for calculating azimuths. GeographicLib can do this much more accurately (though it's not really a huge difference.)

Plus, its tests are rather heavy and I'm a bit wary of the license (cf. pyoceans/python-seawater#16).

This won't pass without conda-forge/staged-recipes#2586 though.

### CODE REVIEW

**Comment by ocefpaf** [comment]
It is only used to build one of the examples. So you need to update the example too.

**Comment by QuLogic** [comment]
It is already updated. Also, fixed a warning from ipykernel.

**Comment by ocefpaf** [comment]
Missed that. But we don't have your alternative packaged. Could you try
https://github.com/axiom-data-science/pygc instead?

**Comment by ocefpaf** [comment]
Thanks @QuLogic. Sorry for the delay to merge this.

**Pull request merged**
