### PR TITLE
Fist step towards better docs.

### PR DESCRIPTION
**Pull request by ocefpaf**
GitHub renders RST so I am ditching the Markdown README and renaming the `.txt` README to `.rst`.  I also added some badges at the top.

@themiurgo Can you review and merge this one?

### CODE REVIEW

**Comment by themiurgo** [comment]
All seems good. Merging.

**Comment by ocefpaf** [comment]
Thanks!

**Comment by themiurgo** [comment]
I also just noticed that `README` and the `docs/index.rst` are basically duplicates (with the latter being more up-to-date).

**Comment by ocefpaf** [comment]
Yep. That is why I started here.  I want to "merge" them into one.

**Pull request merged**
