### PR TITLE
Use leaflet 1.0.0

### LINKED ISSUE #521: Move to leaflet 1.0
http://leafletjs.com/2016/09/27/leaflet-1.0-final.html

### PR DESCRIPTION
**Pull request by juoceano**
Fixes #521 

Tested all the notebooks in the gallery locally and, with a quick visual inspection, they seems to be OK.

### CODE REVIEW

**Comment by juoceano** [comment]
> Tested all the notebooks in the gallery locally and, with a quick visual inspection, they seems to be OK.

Spoke too soon. `MarkedCluster` was nor working... There may be more failures. Do not merge it yet. I will check this with more care tomorrow.

**Comment by juoceano** [comment]
`leaflet.makercluster` is redefined in many places... Maybe that deserves some re-factoring and defining it in a single place.

**Comment by juoceano** [comment]
Commit https://github.com/python-visualization/folium/pull/531/commits/584523e9fd07d853d7dca7604df601890e968a0d fixes the `polyline_text_path`.

**Comment by ocefpaf** [comment]
Awesome!  I tested this locally and found a few more incompatibilities. See #534 but I guess we can merge this and work on that in a separate PR.

**Pull request merged**
