### PR TITLE
Added all WMS options and fleshed out the docs.

### PR DESCRIPTION
**Pull request by ocefpaf**
**This is incomplete!  Do not merge!!**

I am waiting for #274  and #276 to finish this one.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Todo:

- [ ] Added `styles` example.
- [ ] Test all options.
- [ ] Make the layers not enable by default.

**Comment by ocefpaf** [comment]
Most of the work I had for this PR was in my dead laptop.  I will just start over.

**Comment by BibMartin** [comment]
> Most of the work I had for this PR was in my dead laptop. I will just start over.

Sorry about that. I hope you've not lost too much other things.

**Comment by ocefpaf** [comment]
> Sorry about that. I hope you've not lost too much other things.

I did not lose much, just a few things I forgot to commit. I believe I will recover everything too.  The HDD seems fine.  Just could not find time to do it yet.

**Pull request closed without merging**
