### PR TITLE
RawGit Deprecation

### LINKED ISSUE #997: Remove use of rawgit
Rawgit is being deprecated: https://rawgit.com/

We cannot use it for new URL's and have to stop using it for current ones and move to other CDN's before October 2019.

Currently there are 13 places where we use Rawgit:
https://github.com/python-visualization/folium/search?q=rawgit&unscoped_q=rawgit

### PR DESCRIPTION
**Pull request by jtbaker**
Swapped all references to `rawgit.com` to `rawcdn.githack.com`. Pretty sure I got everything. Closes #997.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jtbaker I'm not sure you meant for all those commits, right?

**Comment by Conengmo** [comment]
@jtbaker the xml's ended up being committed again :)  Can you remove them? After that I'll add a changelog entry and merge. Thanks for making this PR!

By the way, what do you use to do git stuff? If you'd like we could maybe share our workflows, see what can be improved.

**Comment by ocefpaf** [comment]
> By the way, what do you use to do git stuff? If you'd like we could maybe share our workflows, see what can be improved.

That is a good question! I'm a big fan of fork-branch-PR. Sometimes I don't even have a master on my fork so I'm forced to always fetch the latest master-dev and branch from there when adding a new feature or fixing a bug.

PS: would you two be available for a live meeting to discuss that and more about `folium`?

**Comment by Conengmo** [comment]
I removed the xmls and added a line to the changelog. Good to merge IMO.

> would you two be available for a live meeting to discuss that and more about folium?

That would be nice! What's a good channel to set this up, Gitter? I should check more often or enable notifications then.

**Comment by Conengmo** [comment]
Merged! Thanks @jtbaker, glad we got this done now already :)

**Comment by jtbaker** [comment]
@Conengmo sorry for the delay on my part, it has been a really busy work week. Thanks for the help! I think early on in my history with the project I accidentally committed the XMLs to my master branch and it has hosed my repository ever since and it is seemingly impossible to get them out of version control - I've tried rebasing my master and PRing from the `folium` main master etc. - I think I just need to close my fork and make a new one.

>PS: would you two be available for a live meeting to discuss that and more about folium?

That sounds great @ocefpaf, I'd like to be a part of it. I'm on US on CDT time.

**Comment by ocefpaf** [comment]
> I think I just need to close my fork and make a new one.

That is one way to fix it. The other one is to remove your `master` locally, re-check `upstream`'s `master` and force push it. It would be something like:

```shell
git checkout upstream/master
git branch -D master
git checkout -b master
git push --set-upstream origin master -f
```

PS: consider having a development cycle without `master`. That way one can always check the latest `master` from `upstream` and start a new feature branch.

**Comment by ocefpaf** [comment]
> That sounds great @ocefpaf, I'd like to be a part of it. I'm on US on CDT time.

@Conengmo and @jtbaker how about November 7th (Wednesday) around 14:00 Eastern? (That should be 13:00 CDT, right @jtbaker?)

**Comment by Conengmo** [comment]
I'm available them. I'm on Central European time so that's 19:00 for me if I'm not mistaken.

**Comment by ocefpaf** [comment]
> I'm available them. I'm on Central European time so that's 19:00 for me if I'm not mistaken.

We can do it sooner then, I don't want to bother you at 19:00 :smile: 

How about 14:00 UTC? That would be 15:00 for @Conengmo, 11:00 to me, and 9:00 for @jtbaker.

**Comment by Conengmo** [comment]
Perfect

**Pull request merged**
