### PR TITLE
Simpler HTML repr

### PR DESCRIPTION
**Pull request by ocefpaf**
I removed all the IPython notebook stuff and simplified the `_repr_html_` to inline the JSONs.  This should allow for just leaving the `map`object as the last line in the notebook and get a rich HTML display as expected.  I made a bunch of examples here:

http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/tree/master/

I appreciate as much input as I can get here before merging.  I am targeting the `v0.1.6` branch and, if this works out there in the wild, we can go for @BibMartin far more elegant [solution](https://github.com/python-visualization/folium/issues/176#issuecomment-131693563).

PS 1: Note that the `geo_path` option does not work.  I wonder if we should treat all GeoJSONs as `geo_str`. If someone finds the time please take a look at the example above and try to find problems.

PS 2: I ran all those notebooks in the latest `Jupyter` and `IPython 2.3.1` with success.

### CODE REVIEW

**Comment by wrobstory** [comment]
uhhhhhhhhhhh these notebooks are amazing. You all are doing such great work.

**Comment by BibMartin** [comment]
This looks great ! I would be okay to merge.
I'll wait 12 more hours to enable others' input

**Comment by ocefpaf** [comment]
> I'll wait 12 more hours to enable others' input

@BibMartin your are much wiser than me :wink:

**Comment by BibMartin** [comment]
I just try to learn from our former mistake :stuck_out_tongue_winking_eye:

**Comment by BibMartin** [comment]
:clock1: It's time to merge. Cheers !

**Comment by ocefpaf** [comment]
Thanks!  `v0.1.6` is almost ready...

**Comment by Conengmo** [comment]
Hi @sertalpbilal, two things, could you open a new issue for these kind of bug reports? And can you try upgrading to the latest version of folium? Should be 0.5 or even the Git master.

**Comment by sertalpbilal** [comment]
@Conengmo Sure, will do!

**Pull request merged**
