### PR TITLE
Add Example FeatureGroup and ClusteredMarker

### PR DESCRIPTION
**Pull request by knil-sama**
How to separate data in different ClusteredMarker for each FeatureGroup so we can toogle them

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks for the example @knil-sama! But I am having trouble visuazling the notebook. Here is the nbviewer message:

http://nbviewer.jupyter.org/github/knil-sama/folium/blob/0e98ea4d593c33106a8468abb8251cc23caaaaac/examples/example_ClusteredMarker_and_FeatureGroup.ipynb

and locally I get:

```
Unreadable Notebook: /example_ClusteredMarker_and_FeatureGroup.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...',)
```

**Comment by ocefpaf** [comment]
Note to self. Travis-CI is not failing as it should in https://travis-ci.org/python-visualization/folium/jobs/178811170#L894

**Comment by knil-sama** [comment]
Ok, will look into the NotJSONError, I should have time to commit another tonight.

**Comment by ocefpaf** [comment]
@knil-sama now it is possible to see you notebook. Thanks!

However, even though that is a nice and clean example, I am not sure it brings anything new. We do have examples that show the use of `FeatureGroup` and `ClusteredMarker` and I would like to keep the gallery here short and concise.

Maybe it would be nice to create another repo with user contributed examples for that.

**Comment by knil-sama** [comment]
Alright so I should put it in something like 
 folium/examples/contrib or folium/examples/advanced ?

**Comment by ocefpaf** [comment]
Let me create a `folium_contrib` repository, that is probably the best place for this. Hold on.

**Comment by ocefpaf** [comment]
Done.  See https://github.com/python-visualization/folium_contrib

I will add some boilerplate stuff there later, like Travis-CI testing, better README, and some notebooks of my own.

Thanks @knil-sama!

**Comment by knil-sama** [comment]
Great, I push it on the new repo, I close this one

**Pull request closed without merging**
