### PR TITLE
Added SideBySide plugin basic funcionality

### PR DESCRIPTION
**Pull request by kikocorreoso**
This PR adds basic functionality provided by [this Leaflet plugin](https://github.com/digidem/leaflet-side-by-side) similar to the [ipyleaflet's SplitMap control](https://ipyleaflet.readthedocs.io/en/latest/api_reference/split_map_control.html).

I've added a notebook in the `examples/` directory.

Please, let me know if there is something wrong or if the plugin is not an interesting plugin for folium.

### CODE REVIEW

**Comment by Conengmo** [comment]
Hi, thanks for submitting this PR! I was working on something similar in #933, based on another Leaflet plugin. No reason to have two split map type of plugins, so which Leaflet plugin do you think is better?

**Comment by kikocorreoso** [comment]
Hi @Conengmo 

Sorry, I didn't see your PR.

Well, maybe there is room for both. I think the functionality is not exactly the same.

**Comment by Conengmo** [comment]
Can you tell a bit about what's the difference?

**Comment by kikocorreoso** [comment]
Well, using the `Sync` plugin you can show and sync two different maps with different layers so it is useful to provide more information on the same area and to visually compare Several maps. 

With the `SideBySide` plugin you can have the same but on the same map window.

So, with `Sync` you have to divide the size of the map window in two or more. With the `SideBySide` you can have a complete view of a map and visually check differences on the same place just moving the control. With `Sync` plugin you can have something similar using the `Sync.Cursor` (https://raw.githack.com/jieter/Leaflet.Sync/master/examples/syncCursor_dual.html) but, again, it is not exactly the same and you have a smaller window for both maps.  On small screens I would like to have the `SideBySide` functionality available and, for me, it would be quicker to just move the control to check the differences on the same pixel (or group of pixels) without having to add more code to use the `Sync.Cursor` functionality.

I think both plugins are useful. `SideBySide` is for a very specific use while `Sync` seems more complete.

I don't know if this answer your question.

**Comment by Conengmo** [comment]
This functionality got merged in https://github.com/python-visualization/folium/pull/1292.

Thank you for your effort @kikocorreoso and apologies this PR didn't work out.

**Comment by kikocorreoso** [comment]
Thanks for adding the functionality 🗺️ !!!!!

**Pull request closed without merging**
