### PR TITLE
Story Map Plugin

### PR DESCRIPTION
**Pull request by Gordonei**
# Overview
I have a use case where I want to create a map with a user controlled timeline, which will change what is on the map. This opens the door for creating narratives on top of folium maps.

My approach was to wrap the [leaflet-timeline-slider](https://github.com/svitkin/leaflet-timeline-slider) plugin in an opinionated way - basically you pass the Python class an iterable of tuples, each with the contents `(<label>, <layer>)`, and it creates a sequential timeline which cycles through the layers in exclusive fashion, i.e. when label 1 is selected, its corresponding layer is visible and centred and all else are removed, when label 2 is selected, layer 2 is selected and everything else is invisible, etc.

In a bid to be flexible, I had to do some slightly ropey stuff with the Jinja template, splitting it into two - one with most of the boiler plate construction, and one after the children have been rendered. This is because the children need to be in place before the timeline slider is instantiated, because it refers to them on page load (I can disable this behaviour on the slider, but I still then need to bootstrap the timeline somehow).

~~In theory, I'm just inheriting from `FeatureGroup`, so this could quite happily live alongside other layers, but to be honest, I haven't tested this extensively - it's outside of my use case. Happy to review a PR making it more robust in this situation, though.~~

I was tempting fate with the above - showed it to my user, and immediately they requested this. Now lives happily alongside other layers, and a layer control.

# Testing
## Unit Tests
All passing, including new test class that I added (`tests/plugins/test_story_map.py`)L
```bash
$ python3 -m pytest tests
========================================= test session starts ==========================================
platform linux -- Python 3.7.5, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/gordon/workspace/folium, inifile: setup.cfg
plugins: forked-1.1.3, cov-2.8.1, xdist-1.31.0, flake8-1.0.4, nbval-0.9.4
collected 144 items                                                                                    

tests/test_features.py ..........                                                                [  6%]
tests/test_folium.py ...............                                                             [ 17%]
tests/test_jinja.py ..............                                                               [ 27%]
tests/test_map.py ........                                                                       [ 32%]
tests/test_raster_layers.py .....                                                                [ 36%]
tests/test_repr.py ...XX                                                                         [ 39%]
tests/test_utilities.py .................................................                        [ 73%]
tests/test_vector_layers.py ......                                                               [ 77%]
tests/plugins/test_antpath.py .                                                                  [ 78%]
tests/plugins/test_beautify_icon.py .                                                            [ 79%]
tests/plugins/test_boat_marker.py ..                                                             [ 80%]
tests/plugins/test_dual_map.py .                                                                 [ 81%]
tests/plugins/test_fast_marker_cluster.py ....                                                   [ 84%]
tests/plugins/test_feature_group_sub_group.py .                                                  [ 84%]
tests/plugins/test_float_image.py .                                                              [ 85%]
tests/plugins/test_fullscreen.py .                                                               [ 86%]
tests/plugins/test_heat_map.py ...                                                               [ 88%]
tests/plugins/test_heat_map_withtime.py .                                                        [ 88%]
tests/plugins/test_marker_cluster.py .                                                           [ 89%]
tests/plugins/test_minimap.py .                                                                  [ 90%]
tests/plugins/test_pattern.py .                                                                  [ 90%]
tests/plugins/test_polyline_offset.py ....                                                       [ 93%]
tests/plugins/test_polyline_text_path.py .                                                       [ 94%]
tests/plugins/test_scroll_zoom_toggler.py .                                                      [ 95%]
tests/plugins/test_story_map.py ....                                                             [ 97%]
tests/plugins/test_terminator.py .                                                               [ 98%]
tests/plugins/test_time_slider_choropleth.py x                                                   [ 99%]
tests/plugins/test_timestamped_geo_json.py .                                                     [100%]

=========================================== warnings summary ===========================================
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:1151
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:1151
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_features
tests/test_folium.py::TestFolium::test_choropleth_key_on
tests/test_folium.py::TestFolium::test_choropleth_key_on
tests/test_folium.py::TestFolium::test_choropleth_key_on
tests/test_folium.py::TestFolium::test_choropleth_key_on
tests/test_folium.py::TestFolium::test_choropleth_key_on
tests/test_folium.py::TestFolium::test_choropleth_key_on
  /usr/lib/python3/dist-packages/pkg_resources/__init__.py:1151: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
    self, resource_name

/usr/local/lib/python3.7/dist-packages/_pytest/mark/structures.py:327
  /usr/local/lib/python3.7/dist-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.web - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

folium/plugins/story_map.py:3
  /home/gordon/workspace/folium/folium/plugins/story_map.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Iterable, OrderedDict

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======================= 141 passed, 1 xfailed, 2 xpassed, 19 warnings in 37.26s ========================
```

## Linting
Seems to be happy:
```bash
$ flake8 folium --max-line-length=120 | grep -i story_map | wc -l
0
```

## Ad-hoc Testing
Added an [example notebook](./examples/StoryMap.ipynb) - uploaded resulting HTML map [here](http://storymap-test-output.s3-eu-west-1.amazonaws.com/Storymap.html):
```bash
$ aws s3api create-bucket --bucket storymap-test-output --region eu-west-1 --create-bucket-configuration LocationConstraint=eu-west-1
{
    "Location": "http://storymap-test-output.s3.amazonaws.com/"
}
$ aws s3 cp Storymap.html s3://storymap-test-output/
upload: ./Storymap.html to s3://storymap-test-output/Storymap.html
$ aws s3api put-object-acl --bucket storymap-test-output --key Storymap.html --acl public-read
```

### CODE REVIEW

**Comment by Gordonei** [comment]
Looks like travis builds breaking are unrelated to my changes: https://travis-ci.org/python-visualization/folium/jobs/648094008?utm_medium=notification&utm_source=github_status

**Comment by Gordonei** [comment]
Looks like @sknzl's commits fixed Travis - I just rebased.

**Comment by Conengmo** [comment]
Hi Gordon, thanks for your PR, it looks great and I appreciate the effort you put into it. I'm responding a bit late because, well it's volunteering, but also because I was a bit hesitant on what to do here.

We don't have a lot of workpower so we have to be careful of keeping folium easily maintainable. We've had issues before with code-heavy plugins, like `TimestampedGeoJson` and `TimeSliderChoropleth`, that are hard to maintain. We have to assume the original author of the plugin won't be around to maintain it.

I recently wrote some plugin acceptance criteria: https://github.com/python-visualization/folium/blob/master/.github/CONTRIBUTING.md#plugin-acceptence-criteria. The basic idea is that folium does two things: 1. wrap Leaflet, and 2. wrap Leaflet plugins. I know this wasn't always applied, but I think it should generally be the case.

Though I like your new feature and it's well written I don't want to include it in the folium library because of the future maintenance burden. Instead, I propose that you host a repo yourself with just this plugin. Add it on PyPI so users can easily install it. We'll link to it from our documentation so folium users find it when they explore folium.

I'd love to hear what you think of this.

**Comment by Gordonei** [comment]
Don't worry about the delay - I scratched my own itch, and the extra work to get it into a PR was marginal :) I use Folium on such a regular basis, so I *really* appreciate the work you and the rest of maintainers put into providing such a valuable resource.

I appreciate the urge to keep folium a reasonably light wrapper around Leaflet, and Leaflet extensions, so happy to refactor into a stand alone package with folium in the `requirements.txt`. If you're happy to link to it, that would be great!

However, before I do that, do you see any way I could wrap [the underlying Leaflet extension](https://github.com/svitkin/leaflet-timeline-slider) in a way that would work in the underlying project?

The reason I went the route that I did was because I couldn't think of a more elegant way to address how it needs the `changeMap` JS function parameter, without using the `MacroElement` iterable abstraction - but maybe there is a more flexible way to do it?

**Comment by Gordonei** [comment]
Hey @Conengmo , sorry to bother you for an answer, but keen to start splitting my code out - do you think there is any way some of the base elements could be kept in Folium, or is the nature of the Leaflet plugin that you have to do something fairly opinionated on top?

**Comment by Conengmo** [comment]
Hi Gordon, good that you're reminding me. I'm not sure what you're asking exactly. Do you mean having the leaflet-timeline-slider plugin being wrapped as a plugin in the folium library? I'm assuming that's what you mean. We could do that, but I don't really see the benefit:

- `L.control.timelineSlider` is quite integrated in your code, so I don't know if it makes sense to take it out.
- If we put `L.control.timelineSlider` in folium, it will be harder for you to make changes to your feature, because you might have to get changes to the folium class that wraps `L.control.timelineSlider` through first.
- I don't really see a use-case for `L.control.timelineSlider` outside of the feature that you're making.

Looking at your code I think it's already good, I don't think it would benefit from splitting stuff off into various places.

**Comment by Gordonei** [comment]
Thanks for the answer, @Conengmo - OK, I'm going to create a new package for this change, as well as one or two reasonably elaborate changes I've made. I've created the shell of the repo [here](https://github.com/Gordonei/folium-sententium).

I'll make a new PR to suggest a link in the folium docs, when it's ready.

Thanks again for your work on folium - I've been working a lot with it lately, and it's great!

**Pull request closed without merging**
