### PR TITLE
Added a minimum working example for the highlight_function

### PR DESCRIPTION
**Pull request by eHanseJoerg**
I added a Jupyter Notebook and some csv data to show how the highlight function works. 
The Jupyter NB depends on pandas, os, folium, json.

Additionally, I added two lines to the docstring in the GeoJson class because the paramter list was incomplete. I did not work on chloropleth class.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @eHanseJoerg!

GitHub makes it hard to review notebooks. So here is a `nbviewer` link to hlelp: http://nbviewer.jupyter.org/github/eHanseJoerg/folium/blob/master/examples/Highlight_Function.ipynb

**Comment by joshuacano** [comment]
Thanks @ehansejorg! I won't be able to add the docstrings for another week when I'm back from vacation, I'd be glad to when I get back.

Joshua Cano

**Comment by ocefpaf** [comment]
Thanks @eHanseJoerg!

**Comment by elochk** [comment]
Thanks for the example! I am trying to plot polygons in the same way, but nothing displays at the map. When I change type "Polygon" to type "LineString" keeping the same coordinates, they are displayed. I would be grateful if you could help with this issue.

**Comment by amirham** [comment]
In the same situation as @elochk, this doesn't seem to work for Polygons.

**Pull request merged**
