### PR TITLE
GeoJsonCss, Search and Updated TimeDimensionGeoJson

### PR DESCRIPTION
**Pull request by ghandic**
Tried to squash the commits - need to touch up on my git...

### CODE REVIEW

**Comment by ocefpaf** [comment]
Are you OK with we reopen the others PRs and do this feature by feature?

**Comment by ghandic** [comment]
Yeah that’s fine, then I can just look at the difference between my master and the upstream master and see what else I changed - still trying to reduce my git mistakes

Sent from my iPhone

On 25 Oct 2017, at 22:54, Filipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you OK with we reopen the others PRs and do this feature by feature?

**Comment by ghandic** [comment]
I didn’t realise, I actually deleted those branches so it won’t let me reopen the merge request I don’t think

**Comment by ocefpaf** [comment]
Yep. GitHub should let you restore them though. Do you want to try that?

**Comment by ocefpaf** [comment]
Another alternative that I could try would be picking the commits from this branch and opening new PRs.
If restoring does not work I might try that.

**Comment by ocefpaf** [comment]
@ghandic both `Search` and the update to `TimeDimensionGeoJson` made into `folium`. We are only missing `GeoJsonCss`. I'm closing this PR b/c it is stale but I believe the effort to implement `GeoJsonCss` is still valid. Maybe @jtbaker may want to give it a try?

**Pull request closed without merging**
