### PR TITLE
Removes warning about conflicts with Draw plugin

### PR DESCRIPTION
**Pull request by fullonic**
PR #1180 fixed this conflict.

### CODE REVIEW

**Comment by Conengmo** [comment]
It did? Seems unlikely doesn't it, since all we did was add the if statement. If that's true, the situation is still the same.

Do you know what the conflict was, and why it's fixed now?

**Comment by fullonic** [comment]
It fixes the conflict because it was related with the javascript type error caused by the Draw plugin. Fixing the js error fixed this conflict. 
Actually, the conflict wasn't only with the LocateControl plugin, I found it as well using the Fullscreen plugin and Draw together. I tested the LocateControl plugin after fixing the Draw js type error and it works without conflicts.

**Comment by Conengmo** [comment]
Thanks for explaining. I haven't tried this out myself but I trust you to have looked into this. 

Before merging this, could you take out the commit that changes `CONTRIBUTING.md`?

**Comment by fullonic** [comment]
@Conengmo, Thanks.
I removed the CONTRIBUTING.md. It was from updating my master branch with the folium master.
Cheers

**Comment by Conengmo** [comment]
Thanks @fullonic! Nice we got this sorted out.

**Pull request merged**
