### PR TITLE
add weights usage to the example HeatMapWithTime

### PR DESCRIPTION
**Pull request by Demetrio92**
I was trying out HeatMapWithTime.ipynb example and it took me a while to figure out exactly how weights works and how I could use them. Weights in heatmaps seem to me to be an essential component, so I extended the example a bit with non-trivial weights.

### CODE REVIEW

**Comment by Demetrio92** [comment]
Code tests fail for a completely unrelated to this PR reason. 

Selenium fails on a __different__ heatmap, so also __not__ related.

**Comment by Demetrio92** [comment]
@Conengmo except for broken tests, this is merge-ready. 

I noticed github does not render the final result when reviewing changes. Here's an nbviewer link for your convenience

https://nbviewer.org/github/Demetrio92/folium/blob/add_weights_usage_to_example_HeatMapWithTime/examples/HeatMapWithTime.ipynb

**Comment by Conengmo** [comment]
Thanks for your work! I’ll try and review it this weekend. Also fix those tests.

**Comment by Conengmo** [comment]
Thanks @Demetrio92!

**Pull request merged**
