### PR TITLE
Popup can accept strings explicitly

### PR DESCRIPTION
**Pull request by jelmelk**
This is to address https://github.com/python-visualization/folium/issues/259. Assuming I did the PR properly.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Awesome @jelmelk!  Thanks for the PR!

Can you build a test for this behavior?

**Comment by jelmelk** [comment]
Am I correct to assume you're talking about test_folium.py?

**Comment by ocefpaf** [comment]
You are adding this behavior for `Marker`, ` CircleMarker`, and `RegularPolygonMarker`.  Correct?

I guess we should also add this for lines...

**Comment by ocefpaf** [comment]
> Am I correct to assume you're talking about test_folium.py?

Yep.

**Comment by jelmelk** [comment]
> You are adding this behavior for Marker, CircleMarker, and RegularPolygonMarker. Correct?

Yes, those are the only ones that needed it. So would it be a single function for each one?

**Comment by ocefpaf** [comment]
> Yes, those are the only ones that needed it. So would it be a single function for each one?

Maybe we could have been more clever and try to avoid that repetition, but your implementation is OK. I will take a better look tomorrow (going to bed now).

@BibMartin any observations?

**Comment by jelmelk** [comment]
I agree, but like I said in https://github.com/python-visualization/folium/issues/259#issuecomment-160141767 it could be done individually or in one spot that catches all three. Let me know tomorrow, I can change it if needed.

**Comment by BibMartin** [comment]
Hi @jelmelk ; thanks for the PR !
Provided the `Marker` class is very simple, I think you can implement it only in `Marker` and let the other classes inherit from it. 
BTW it would make sens to have all marker stuff inherit from the same root class.
Anyway, we're only sparing 6 lines of code this way :arrow_right:  it's not strategic and I would accept the PR like this.

**Comment by jelmelk** [comment]
Due to the branch mix up on my part, I'm closing this PR.

**Pull request closed without merging**
