### PR TITLE
GeoJSON popup.

### LINKED ISSUE #100: Geojson popup content not showing up
I have a geojson (tri.json) which has polygons with popup content. When I plot it with folium as follows, the popup does not work. If I import my json at [geojson.io](http://bl.ocks.org/d/2f2489bb1bfb94650b21) the popup works fine.

What may be going wrong?

**tri.py**
```
    import folium

    # Map origin
    cx = -117.7495299743632
    cy = 35.74053999839425

    # Set center and zoom level of the map
    map_1 = folium.Map(location=[cy, cx], zoom_start=12,)

    # Mark center - this popup works
    #map_1.polygon_marker(location=[cy,cx], popup=str('This one works'))

    # Add patches to the map
    map_1.geo_json(geo_path='tri.json')

    map_1.create_map(path="tri.html", plugin_data_out=True)
```

**tri.json**
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -117.7495299744,
              35.7405399984
            ],
            [
              -117.7422264169,
              35.7472081889
            ],
            [
              -117.7521555454,
              35.7536368252
            ]
          ]
        ]
      },
      "type": "Feature",
      "id": 1,
      "properties": {
        "name": "AirportLake,Subsection0",
        "popupContent": "sid:1 fault:AirportLake,Subsection0"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by ocefpaf**
This closes  #100 and #3.  Request #6 is a little bit trickier and will demand more thinking.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@birdage Can you review.  I hard-coded the `onEachFeature` call and I am unsure of the impact on non-pop GeoJSONs.

**Comment by birdage** [comment]
@ocefpaf this one cant be merged

**Comment by ocefpaf** [comment]
@birdage rebased and over to you.

**Comment by birdage** [comment]
looks good

**Comment by oztalha** [comment]
Thanks, not tested but looks awesome ! I have a quick follow-up request though: In geoJSON file I only have the polygon data (and I don't want to modify the file), I think this is the case for most of the people. And I would like to keep popup contents in other places such as a columns in a pandas dataframe or in a JSON (I can modify the file produced by data_out=data.json) as I would like to create maps with different popup contents but with the same layout. So, could you please also extend the feature so that we could be able to feed the popup content via **data_1** JSON as an alternative to **gjson_1** JSON ? Thanks again !

**Comment by ocefpaf** [comment]
Hi @oztalha,

We are running a little low on man power.  To make sure your request will be attended one day you should open a new issue with that.  We do not look for pending actions on merged PR and closed issues.

(Also, patches are welcome :stuck_out_tongue_winking_eye: )

**Comment by oztalha** [comment]
Thanks. I will move out of my comfort zone and hopefully learn JS soon; then see me :-)

**Pull request merged**
