### PR TITLE
Fix #64: Remove margins from leaflet-tiles

### LINKED ISSUE #64: Tile alignment in ipython notebook
On my notebooks the first tile is always offset.
It seems there is a top margin for all but the first tile
because of the following css selector in style.css:

```css
.rendered_html * + img
```

maybe adding some css to override margins is an good idea

### PR DESCRIPTION
**Pull request by lennart0901**
This fixes #64

### CODE REVIEW

**Comment by lennart0901** [comment]
Before patch
before


After patch:
after

**Comment by ocefpaf** [comment]
@lennart0901 Thanks!  Just one last request.  Can you add that notebook to a gist (or something similar) so we can get a nbviewer URL.  That way we can refer to it in the Changelog file.

@birdage BTW we should start a Changelog file!

**Comment by lennart0901** [comment]
https://gist.github.com/lennart0901/b158758d262c58b54c1d

**Comment by ocefpaf** [comment]
@lennart0901 thanks again!

**Pull request merged**
