### PR TITLE
Update changelog for 1.0 release

### PR DESCRIPTION
**Pull request by Conengmo**
@ocefpaf let's do a 1.0 release! If you agree, here's what I think we should do:

I will:

- Add a changelog for Branca.
- Merge this PR.

Afterwards, you can:
- Make a Branca 0.7.0 release.
- Make a Folium 1.0.0 release.

What are your thoughts on this?

### CODE REVIEW

**Comment by martinfleis** [comment]
Shall we include #1793 and possibly https://github.com/python-visualization/branca/pull/134 before releasing?

**Comment by ocefpaf** [comment]
It is a long weekend here but I'll try to get to this ASAP. If not, next Monday.

**Comment by martinfleis** [comment]
I guess that we should resolve #1803 before releasing as well.

**Comment by Conengmo** [comment]
I'll use these when we make a 0.15.0, but this PR can be closed.

**Pull request closed without merging**
