### PR TITLE
Implement measure plugin closes #472

### LINKED ISSUE #472: How to measure distance?
Is there a way to enable the measure feature of Leaflet with Folium?
image

### PR DESCRIPTION
**Pull request by ocefpaf**
@BibMartin I went for https://github.com/ljagis/leaflet-measure instead of https://github.com/jtreml/leaflet.measure

`ljagis/leaflet-measure` seems more up to date, works fine with latest leaflet, and has more functionalities.

### CODE REVIEW

**Comment by BibMartin** [comment]
Too late to help @ocefpaf ; sorry.
Good new feature though !

**Comment by ocefpaf** [comment]
> Too late to help @ocefpaf ; sorry.

Sorry. I assumed you were busy with day job and did not ping you.
But it is never too late :wink: 
Let me know if you have any review actions and I'll prepare another PR immediately.

> Good new feature though !

Indeed. I would like to a hook to save the GeoJson afterwards. They have an example to print the points on the screen, but not to add a "save" button.

**Comment by BibMartin** [comment]
> Sorry. I assumed you were busy with day job and did not ping you.
> But it is never too late :wink:

Day job is pulling quite much therefore I cannot be as involved as I used to be ; but I'll try to answer when you ping me.

**Comment by ocefpaf** [comment]
> Day job is pulling quite much therefore I cannot be as involved as I used to be ;

I understand. I can only work on `folium` when it overlaps with the day job interests :unamused: 

> but I'll try to answer when you ping me.

Thanks! Next time I'll wait a few days before self-merging :smile:

**Comment by cristi-neagu** [comment]
Silly question, but how is this supposed to work? Can anyone please provide a short code snippet?

**Comment by BibMartin** [comment]
https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/plugin-MeasureControl.ipynb

**Pull request merged**
