### PR TITLE
pep8 test

### PR DESCRIPTION
**Pull request by ocefpaf**
Fear the :ghost: @BibMartin :wink:

### CODE REVIEW

**Comment by ocefpaf** [comment]
It is failing as expected.  I will fix the offending lines in this PR.  Do not merge this yet.

**Comment by BibMartin** [comment]
@ocefpaf 

> Fear the :ghost: @BibMartin :wink:

This will be of huge help against nasty bad programmers like me.
I may have to switch to a more permissive project :wink:

> It is failing as expected. I will fix the offending lines in this PR. Do not merge this yet.

ok, no problem.

**Comment by ocefpaf** [comment]
@BibMartin everything passes but,

```shell
The command "find ./folium -type f -name "*.py" | xargs flake8 --max-line-length=100" exited with 0.
0.41s$ find ./tests -type f -name "*.py" | xargs flake8 --max-line-length=100
./tests/test_folium.py:366:9: F841 local variable 'geo_json' is assigned to but never used
./tests/test_folium.py:464:9: F841 local variable 'geo_json' is assigned to but never used
./tests/test_folium.py:466:9: F841 local variable 'color_scale' is assigned to but never used
```

Are creating those as place holder for a future test?  Or do we need the variable creation for the test?
If it is the latter I can skip those lines in the test, if it is the former I'd rather fix that.

**Comment by ocefpaf** [comment]
@python-visualization/folium before merging this PR I want to know if we have to merge something else first.  Let's avoid painful rebases :smile:

**Comment by BibMartin** [comment]
There's no easy moment for :ghost:ing !
I have #317 and #297 cooking, that can be merged quite quickly (I think) ; but it would not be very painful if they come after this PR.
If others are ok ; I would give priority to this one.

**Comment by ocefpaf** [comment]
> but it would not be very painful if they come after this PR.

Still, let me handle the maintenance/heavy lifting while you keep your creative/new code streak :wink:

**Comment by ocefpaf** [comment]
> I have #317 and #297 cooking

Those two are merged!  Now all I need to know is what do you want to do about https://github.com/python-visualization/folium/pull/323#issuecomment-171753062.  After we sort that out we can merge this one.

**Comment by BibMartin** [comment]
Sorry ; I forgot to answer.
I have nothing clever planned. I guess it's a collateral effect of refactorings and would drop them.

**Comment by ocefpaf** [comment]
Rebased and good to go!

**Comment by BibMartin** [comment]
ok, go!

**Comment by ocefpaf** [comment]
Thanks @BibMartin!

**Pull request merged**
