### PR TITLE
Image overlay tweaks

### PR DESCRIPTION
**Pull request by andrewgiessel**
I think… this is it.

### CODE REVIEW

**Comment by andrewgiessel** [comment]
ah, almost.  I have stuff in folium.py.  one sec!

**Comment by andrewgiessel** [comment]
Just for reference, this is the old PR

https://github.com/python-visualization/folium/pull/168/files

The only files I changed in that huge list of changes that got merged into the PR are:  folium.py, folium_tests.py and utilities.py.  I think this matches those changes exactly.

**Comment by ocefpaf** [comment]
@andrewgiessel I just merged this and I am playing with it before the release.  First thing I note is that you chose `opacity` for transparency.  How about changing it to `alpha`, to be more "matplotlib-ish"?

**Comment by ocefpaf** [comment]
And the default of 0.25 might be too transparent, maybe 0.65?  Or even 1 and let the user change it?

**Comment by ocefpaf** [comment]
We are almost there!  Specifying a local file or URL works, but the numpy array seems to be buggy:

http://nbviewer.ipython.org/gist/ocefpaf/7c9a0a5ec354ab9d3238

@andrewgiessel Can you take a look at it?

**Comment by andrewgiessel** [comment]
@ocefpaf How about 0.5?  I set it that low because I use data overlays and I want to see the map underneath.  If it's photographs or landsat, then it's probably something different.

re: numpy array:  what is the shape of `data = plt.imread('itaguare_cropped.jpg')`?

**Comment by andrewgiessel** [comment]
also, keep in mind that if a file or URL string, there is no re-projection done, and to have it match the underlying map projection it needs to be in web mercator.

for numpy arrays, by default, we assume geodetic arrays and project them.  I think the doc string could be clearer...

**Comment by ocefpaf** [comment]
> @ocefpaf How about 0.5? I set it that low because I use data overlays and I want to see the map underneath. If it's photographs or landsat, then it's probably something different.

I am leaning towards `1` and letting the user adjust the opacity.  Pinging @Bibmartin and @themiurgo  for more votes here.

> I think the doc string could be clearer...

Indeed!  If you want to patch it up just make sure to work on the updated `v0.1.6` branch.

> re: numpy array: what is the shape of data = plt.imread('itaguare_cropped.jpg')?

`data.shape = (484, 686, 3)`.  The bug seems to be in the `write_png()` function.  (See http://nbviewer.ipython.org/gist/ocefpaf/227104bc764fb78951cf)

**Comment by BibMartin** [comment]
I would agree that default opacity is `1` : this is the only *natural* default value, and it's the default value for most systems (Leaflet, Matplotlib, ...).
As for the option name, I have a slight preference for `alpha` because python users are used to it.

Anywa

**Pull request merged**
