### PR TITLE
Build docs again.

### PR DESCRIPTION
**Pull request by ocefpaf**
Travis-CI is giving us a hard time. This moves the docs to GitHub Actions and fixes the build. We are losing the versioned docs here but I don't think that is too important b/c old docs do live in GH if folks need them.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@Conengmo I'd love a second pair of eyes here. I'd like to issue a patch release afterwards so we can ship functional docs with it.

**Review by Conengmo — APPROVED** [review]
The changes to the docs themselves look good.

I can't comment that much on the Actions workflow. It makes sense to me. Though I'm not that familiar with how the docs work currently. Were you able to test this workflow?

> We are losing the versioned docs here but I don't think that is too important b/c old docs do live in GH if folks need them.

That's okay with me if that's what it takes to get this working again without Travis.

I'll leave the merging to you.

**Comment by Conengmo** [comment]
@ocefpaf unrelated note, would you mind squashing commits when you merge PR's?  I use https://github.com/python-visualization/folium/commits/main a lot and since we're very much PR oriented instead of commit oriented I'd love to have a clean overview here.

**Comment by ocefpaf** [comment]
> @ocefpaf unrelated note, would you mind squashing commits when you merge PR's? I use https://github.com/python-visualization/folium/commits/main a lot and since we're very much PR oriented instead of commit oriented I'd love to have a clean overview here.

Done!

If this passes it should be good to go.

**Review by Conengmo — APPROVED** [review]
Let's give it a go!

**Comment by ocefpaf** [comment]
The test needs to be updated. Working on it...

**Comment by ocefpaf** [comment]
> The test needs to be updated. Working on it...

Ideally we should make a release of branca so this passes everywhere and not only on latest. I can work on that today.

**Comment by Conengmo** [comment]
Done: https://github.com/python-visualization/branca/commit/9ec0805060e9ba5334e45b5e467ef7f4985d248c

**Pull request merged**
