### PR TITLE
Ignore build results

### PR DESCRIPTION
**Pull request by 1kastner**

### CODE REVIEW

**Comment by Conengmo** [comment]
@ocefpaf was there a reason we did not have a `.gitignore` file before?

**Comment by 1kastner** [comment]
I could not find any good reason for not having one...

**Comment by ocefpaf** [comment]
> @ocefpaf was there a reason we did not have a `.gitignore` file before?

With multiple contributors we had different `.gitignore` b/c people had different policies. I'm OK having one though. Let me review this one...

**Comment by ocefpaf** [comment]
Thanks @1kastner for the `.gitignore` and @Conengmo for the review!

**Pull request merged**
