### PR TITLE
Merge branch 'plugins'

### PR DESCRIPTION
**Pull request by BibMartin**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Awesome!  I really like your vision for this implementation.

@themiurgo since you reviewed most of this PR how far are we from merging?

**Comment by BibMartin** [comment]
@ocefpaf @themiurgo I'm a bit bolcked by this PR : if I want to go further on plugins, I don't know whether I shall commit them on the `master` branch or on `plugins`.
Do you think this can be merged soon ? Or how shall I manage the thing, please ?

PS: sorry for that (most probably) silly question.

**Comment by ocefpaf** [comment]
> sorry for that (most probably) silly question.

Not at all!  But since this is a big change lets wait for more eyes here.  I am :+1:

What do you say @themiurgo?

**Comment by themiurgo** [comment]
I think either way is fine, as long as we keep master working. If you feel it's stable, merge it with master. If you want to have some more freedom to ~~break~~ experiment, continue on a separate branch. I am fine with either choice.

**Comment by ocefpaf** [comment]
Lets merge than, even if we have to breack things later.  People "follow" master and we are getting PRs (#166, #152) that should be using this logic.

**Pull request merged**
