### PR TITLE
Add HERE map tiles example

### PR DESCRIPTION
**Pull request by deeplook**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Cool use of `ipywidgets` there :+1:

**Comment by deeplook** [comment]
Seems like your Travis-CI failed, but I have no clue, why...

**Comment by ocefpaf** [comment]
I guess this failure is expected :smile: 

[`AssertionError: Error: Environment variable HEREMAPS_APP_ID not found`](https://travis-ci.org/python-visualization/folium/jobs/269538356)

To be honest most of the notebooks here belong in https://github.com/python-visualization/folium_contrib and not in this folder. Don't worry about it though.

Let me take this opportunity to finally "fix" the `folium_contrib` gallery and I'll move this notebook there along with the others.

**Comment by deeplook** [comment]
Ok, sounds good!

**Pull request merged**
