### PR TITLE
Use firefox headless instead of phantomjs 

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/python-visualization/folium/issues/891

I chose firefox b/c it is easier to test on Travis-CI and we found some rendering issues with chrome/chromium in the past. 

PS: @Conengmo the `_png()` is not a first class citizen yet. Not sure what else we could do to make it more robust. Maybe a driver selection option?

### CODE REVIEW

**Comment by Conengmo** [comment]
Looks good, and the tests work fine. Only problem is that the temporary file doesn't work on Windows. We had this problem before:
https://docs.python.org/3.6/library/tempfile.html#tempfile.NamedTemporaryFile

I'll see if I can find a solution, otherwise we'll merge it as is.

**Comment by Conengmo** [comment]
I can get the tempfile stuff to work if instead of using `NamedTemporaryFile` we use the underlying `mkstemp` function. We have to close and delete the file ourselves, but it's not that hard.

```
@contextmanager
def _tmp_html(data):
    """Yields the path of a temporary HTML file containing data."""
    filepath = ''
    try:
        f_int, filepath = tempfile.mkstemp(suffix='.html', prefix='folium_')
        os.write(f_int, data.encode('utf8'))
        os.close(f_int)
        yield filepath
    finally:
        if os.path.isfile(filepath):
            os.remove(filepath)
```

Note that this returns the file path, not a file descriptor. What do you think @ocefpaf?

**Comment by ocefpaf** [comment]
@Conengmo I'll take a look at the failures later but it seems that only Python 2.7 is affected and, b/c this feature is not really ready for prime time, I'm OK making it Python 3 only. (We already agreed that the next release is the last one for Python 2.7 anyway.)

**Comment by ocefpaf** [comment]
~~@Conengmo I'll take a look at the failures later but it seems that only Python 2.7 is affected and, b/c this feature is not really ready for prime time, I'm OK making it Python 3 only. (We already agreed that the next release is the last one for Python 2.7 anyway.)~~

Spoke too soon. All the failures were related to new `pytest` version. This one is good to go now.

**Comment by ocefpaf** [comment]
Merging this to b/c of the Travis-CI fixes in the last commit are needed.

**Pull request merged**
