### PR TITLE
Add subdomains option for TileLayer

### PR DESCRIPTION
**Pull request by damselem**
Some tile services use a different set of subdomains. For reference: http://leafletjs.com/reference-1.0.3.html#tilelayer-subdomains

### CODE REVIEW

**Comment by ocefpaf** [comment]
I am 👍 to that change. Can you update the test template to reflect the extra line:
`subdomains: {{this.subdomains}}` and add a test case for something that is different from the default argument?

We need a changelog entry for that.

Bonus if you add a notebook to our gallery with a few use cases 😄

**Comment by damselem** [comment]
Do you agree this should bump the minor version?

**Comment by ocefpaf** [comment]
> Do you agree this should bump the minor version?

Makes sense. Don't forget to add a changelog entry.

**Comment by damselem** [comment]
Is there anything else that needs to be done in order to get this merged?

**Comment by ocefpaf** [comment]
> Is there anything else that needs to be done in order to get this merged?

Nope. I've just been awfully busy with the day job.

Thanks for the PR!

**Pull request merged**
