### PR TITLE
Fix #371

### LINKED ISSUE #371: FeatureGroup name argument ignored?
Hello everyone,

I am trying to set a ``FeatureGroup`` name for a set of ``PolyLine``s, but the name I give to the ``FeatureGroup`` isn't sticking in the map layer control menu.  Instead, a ``macro_element_...`` is returned.

I've set up an [example Jupyter Notebook](http://nbviewer.jupyter.org/github/brwst/folium/blob/master/FeatureGroup_name.ipynb). (in the style of pull request #242) showing this behavior.  Should this be expected?

### PR DESCRIPTION
**Pull request by BibMartin**
Hi @ocefpaf,
this needs to be cherry-picked on the branch `v0.2`.
I don't know how we should deal with this: shall we do a `v0.2.1` to incorporate the fix ? wait for more bugfixes and do a `v0.2.1` in a few weeks ?

### CODE REVIEW

**Comment by BibMartin** [comment]
I cannot figure out what's going wrong with the tests (and cannot reproduce it)

**Comment by ocefpaf** [comment]
> I cannot figure out what's going wrong with the tests (and cannot
reproduce it)

I am away in a conference. I'll take a look, merge, and backport to a
release as soon as I get back.

PS0: since this is a bugfix we should cut a v0.2.1, but no need to wait for
more stuff. We can always cut another v0.2.x series.

PS1: The failure is relate to conda and not folium. I am already looking
into it for another project.

**Comment by BibMartin** [comment]
Ok, great! no hurry, we have a workaround in #371 meanwhile.

**Comment by BibMartin** [comment]
@ocefpaf Oups, it seems we forgot this one.
If you have time to review, merge and cherry pick...

**Comment by ocefpaf** [comment]
This was disappeared from both our radars :wink:

**Pull request merged**
