### PR TITLE
Adding popup to lines, test_line

### PR DESCRIPTION
**Pull request by themiurgo**
This adds the possibility to visualise popups when clicking on lines.

Tests still pass. Let me know if there's anything I need to change to get this merged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Looks good.  I just tested it out:

http://nbviewer.ipython.org/gist/ocefpaf/1360f49bb2bb632a7736

Our tests are lacking a `line` test.  If you think it is a low hanging fruit can you add one and test your modification?  If not I will merge "as is" and add one later.

**Comment by themiurgo** [comment]
Yes, true, no tests. Also, I think there's no documentation about line, I had to see the code to use it. Will see if I can quickly write something in the next couple of days.

**Comment by ocefpaf** [comment]
Great.  If not just open an issue and ping me to get this merged.

**Comment by themiurgo** [comment]
Managed to add tests and documentation. Let me know if it needs some fixups.

**Comment by ocefpaf** [comment]
Python 3.3 is giving us a slap on the wrist.  Probably something simple to solve.  Do you have an env there to check this and fix?  If not I can do later today.

**Comment by themiurgo** [comment]
Not yet, I have been procastinating the Py3 installation. I guess it's about time to get it installed. :grinning:

**Comment by ocefpaf** [comment]
... and now it is Python 3.4 it is hard to make py3k happy!

**Comment by themiurgo** [comment]
What's funny is that the only file that I changed since the last commit (which Travis doesn't complain about), is the index.rst in the docs. I guess some doctest is failing?

**Comment by ocefpaf** [comment]
Nope, we do not run doctest.  The tests are simply:

https://github.com/themiurgo/folium/blob/lines_popup/.travis.yml#L26

Probably something :hankey:  in our tests.

If you are done editing I will merge this and check it here.

**Comment by themiurgo** [comment]
Yes, you can go ahead.

**Comment by ocefpaf** [comment]
Thank @themiurgo!

**Pull request merged**
